
obj-y:=

obj-$(CONFIG_LCD_HD44780U) += lcd_hd44780u.rel
obj-$(CONFIG_LCD_PCF2119X) += lcd_pcf2119x.rel
obj-$(CONFIG_LCD_NHDC0216AZ) += lcd_nhdc0216az.rel
obj-$(CONFIG_LCD_NHDC0216CIZ) += lcd_nhdc0216ciz.rel
