obj-y += mach.rel
obj-$(CONFIG_MEM) += mem.rel
obj-$(CONFIG_SBI) += sbi.rel
obj-$(CONFIG_TIMER) += gpt.rel
obj-$(CONFIG_MMU) += mmu.rel
obj-$(CONFIG_VAISRA_UART) += uart.rel
obj-$(CONFIG_SHUTDOWN) += shutdown.rel
obj-$(CONFIG_VAISRA_BOOT_RAM) += vaisra.rel
