obj-y :=

obj-$(CONFIG_HANOITOWER) += hanoitower.rel
obj-$(CONFIG_SHA256) += sha256.rel
obj-$(CONFIG_MD5) += md5.rel

obj-$(CONFIG_CFFT) += cfft/
obj-$(CONFIG_JPGENC) += jpgenc/
obj-$(CONFIG_GENANN) += gen_ann/
