# Copyright (C) 2008 by Lv Zheng <lv.zheng@soliton.com.cn>
#
# Licensed under the GPL v2, see the file LICENSE in this tarball.

obj-y:=

obj-$(CONFIG_USB) += usb.rel
obj-$(CONFIG_USB_DEV) += usb_dev.rel
obj-$(CONFIG_USB_HCD) += usb_hcd.rel
obj-$(CONFIG_USB_OTG) += usb_otg.rel

obj-$(CONFIG_USB_HID) += usb_hid.rel
obj-$(CONFIG_HID_KBD) += hid_kbd.rel

obj-$(CONFIG_USB_MSD) += usb_msd.rel
obj-$(CONFIG_MSD_SCSI) += msd_scsi.rel
obj-$(CONFIG_MSD_BBB) += msd_bbb.rel

obj-$(CONFIG_USB_SCD) += usb_scd.rel
obj-$(CONFIG_USB_CCID) += usb_ccid.rel
obj-$(CONFIG_USB_ICCD) += usb_iccd.rel
obj-$(CONFIG_SCD_ESC_NONE) += scd_none.rel
obj-$(CONFIG_SCD_ESC_PN53X) += scd_pn53x.rel

obj-$(CONFIG_USB_DFU) += usb_dfu.rel
