obj-y :=

obj-$(CONFIG_NCORE) += ncore.rel
obj-$(CONFIG_MONACO) += monaco.rel
obj-$(CONFIG_CCN512) += ccn512.rel
obj-$(CONFIG_CCI550) += cci550.rel
obj-$(CONFIG_CMN600) += cmn600.rel
obj-$(CONFIG_CMN600_CML) += cmn600_cml.rel
obj-$(CONFIG_N100) += n100/
