obj-y :=

obj-$(CONFIG_NS16550) += ns16550.rel
obj-$(CONFIG_DW_UART) += dw_uart.rel
obj-$(CONFIG_UART_PL01X) += uart_pl01x.rel
obj-$(CONFIG_SEGGER_RTT) += segger_rtt.rel
obj-$(CONFIG_DW_UART_BIRD) += dw_uart_bird.rel
