
obj-y :=

obj-y += board.rel
obj-y += irq.rel
obj-y += tsc.rel

obj-$(CONFIG_GPT_AT90SCR100) += gpt.rel
obj-$(CONFIG_USB_AT90SCR100) += usb.rel
obj-$(CONFIG_WDT_AT90SCR100) += wdt.rel
obj-$(CONFIG_UART_AT90SCR100) += uart.rel
obj-$(CONFIG_LED_AT90SCR100) += led.rel
obj-$(CONFIG_IFD_AT90SCR100) += ifd.rel
obj-$(CONFIG_KBD_AT90SCR100) += kbd.rel
obj-$(CONFIG_TWI_AT90SCR100) += twi.rel
