# Copyright (C) 2008 by Lv Zheng <lv.zheng@soliton.com.cn>
#
# Licensed under the GPL v2, see the file LICENSE in this tarball.

obj-y:=

obj-y += inet.rel
obj-y += raw.rel

obj-$(CONFIG_INET_UDP) += udp.rel
obj-$(CONFIG_INET_TCP) += tcp.rel
