
obj-y:=

obj-y += board.rel
obj-y += irq.rel
obj-y += tsc.rel
obj-y += pm.rel

head-y := head.rel
extra-y := $(head-y)

obj-$(CONFIG_GPT_AT8XC5122) += gpt.rel
obj-$(CONFIG_KBD_AT8XC5122) += kbd.rel
obj-$(CONFIG_UART_AT8XC5122) += uart.rel
obj-$(CONFIG_USB_AT8XC5122) += usb.rel
obj-$(CONFIG_IFD_AT8XC5122) += ifd.rel
obj-$(CONFIG_DSU_AT8XC5122) += boot.rel
