obj-y :=

obj-y += rsdp.aml.rel
obj-y += xsdt.aml.rel
obj-y += fadt.aml.rel
obj-y += dsdt.aml.rel
obj-y += rhct.aml.rel
obj-y += madt.aml.rel
obj-y += spcr.aml.rel
obj-$(CONFIG_SPIKE_ACPI_RIMT) += rimt.aml.rel
