# Copyright (C) 2008 by Lv Zheng <lv.zheng@soliton.com.cn>
#
# Licensed under the GPL v2, see the file LICENSE in this tarball.

obj-y:=

obj-y += fonts.rel

obj-$(CONFIG_FONT_SUN8x16)   += font_sun8x16.rel
obj-$(CONFIG_FONT_SUN12x22)  += font_sun12x22.rel
obj-$(CONFIG_FONT_8x8)       += font_8x8.rel
obj-$(CONFIG_FONT_8x16)      += font_8x16.rel
obj-$(CONFIG_FONT_6x11)      += font_6x11.rel
obj-$(CONFIG_FONT_7x14)      += font_7x14.rel
obj-$(CONFIG_FONT_10x18)     += font_10x18.rel
obj-$(CONFIG_FONT_PEARL_8x8) += font_pearl_8x8.rel
obj-$(CONFIG_FONT_ACORN_8x8) += font_acorn_8x8.rel
obj-$(CONFIG_FONT_MINI_4x6)  += font_mini_4x6.rel
