# Should be passed from command line
# CONFIG_BENCH_STATIC=y

CC=$(CROSS_COMPILE)gcc
STRIP=$(CROSS_COMPILE)strip

ifeq ($(CONFIG_BENCH_STATIC),y)
	CFLAGS_static=-static
	CFLAGS_static_libgcc=-static-libgcc
endif

CFLAGS_align = \
	-falign-functions=1 \
	-falign-jumps=1 \
	-falign-labels=1 \
	-falign-loops=1
CFLAGS_debug = \
	-g \
	-fomit-frame-pointer \
	-fno-unwind-tables \
	-fno-asynchronous-unwind-tables
CFLAGS_warn = \
	-Wall \
	-Wshadow \
	-Wwrite-strings \
	-Wundef \
	-Wstrict-prototypes \
	-Wunused \
	-Wunused-parameter \
	-Wunused-function \
	-Wunused-value \
	-Wmissing-prototypes \
	-Wmissing-declarations \
	-Wno-format-security \
	-Wdeclaration-after-statement \
	-Wold-style-definition
CFLAGS =-DHOSTED -DCONFIG_FP=1 \
	$(CFLAGS_static_libgcc) \
	-finline-limit=0 \
	-ffunction-sections \
	-fdata-sections \
	-fno-builtin-strlen \
	-fno-builtin-printf \
	-funsigned-char \
	$(CFLAGS_align) \
	$(CFLAGS_warn) \
	$(CFLAGS_debug)

#	-fno-guess-branch-probability \

%.o: %.c
	@echo " CC     $<"
	@echo "$(CC) $(CFLAGS) $(CFLAGS_$*) -c $< -o $@"
	@$(CC) $(CFLAGS) $(CFLAGS_$*) -c $< -o $@

%.unstrip: %.o
	@echo " LD     $<"
	@$(CC) $(CFLAGS) $(CFLAGS_$*) $(CFLAGS_static) $< -o $@ $(LIBS_$*)
	@cp -f $@ $(basename $<).debug

%.elf: %.unstrip
	@echo " STRIP  $<"
	@$(STRIP) -s --remove-section=.note --remove-section=.comment $< -o $@
