all: memtester

CC=$(CROSS_COMPILE)gcc
CFLAGS=-O2 -DHOST -DPOSIX -D_POSIX_C_SOURCE=200809L \
	-D_FILE_OFFSET_BITS=64 -DCONFIG_MEMTESTER_NARROW_WRITES
LDFLAGS=-s

memtester.o: memtester.c
	$(CC) $(CFLAGS) -c $< -o $@

memtester: memtester.o
	$(CC) $(LDFLAGS) $< -o $@

clean:
	@rm -f memtester
	@rm -f *.o
