# Copyright (C) 2008 by Lv Zheng <lv.zheng@soliton.com.cn>
#
# Licensed under the GPL v2, see the file LICENSE in this tarball.

obj-y:=

obj-y += usb_msd.rel
obj-$(CONFIG_MSD_SCSI) += msd_scsi.rel
obj-$(CONFIG_MSD_BBB) += msd_bbb.rel
