
ifeq ($(COMPILER),)
COMPILER	:= gcc
endif
ifeq ($(CROSS_COMPILE),)
ifeq ($(RISCV64),)
CROSS_COMPILE	:= riscv32-linux-
else
#CROSS_COMPILE	:= riscv64-linux-
CROSS_COMPILE	:= riscv64-unknown-linux-gnu-
endif
endif
