# Copyright (C) 2008 by Lv Zheng <lv.zheng@soliton.com.cn>
#
# Licensed under the GPL v2, see the file LICENSE in this tarball.

obj-y:=

obj-$(CONFIG_IFD) += ifd.rel
obj-$(CONFIG_IFD_T0) += ifd_t0.rel
obj-$(CONFIG_IFD_T1) += ifd_t1.rel

obj-$(CONFIG_PCD) += pcd.rel
obj-$(CONFIG_PCD_A) += pcd_a.rel
obj-$(CONFIG_PCD_B) += pcd_b.rel

obj-$(CONFIG_COS) += cos.rel

obj-$(CONFIG_ICC) += icc.rel
