obj-y:=

obj-$(CONFIG_IFD_SERIAL) += ifd_serial.rel
obj-$(CONFIG_COS_SCOS) += scos.rel
obj-$(CONFIG_ACR122) += acr122.rel

obj-$(CONFIG_PN53X) += pn53x.rel
obj-$(CONFIG_PN53X_STUB) += pn53x_stub.rel
obj-$(CONFIG_PN53X_SPI) += pn53x_spi.rel
