# Copyright (C) 2008 by Lv Zheng <lv.zheng@soliton.com.cn>
#
# Licensed under the GPL v2, see the file LICENSE in this tarball.

obj-y:=

obj-y += scsi_core.rel
obj-$(CONFIG_SCSI_TARGET) += scsi_trgt.rel
obj-$(CONFIG_SCSI_SBC) += scsi_sbc.rel
