EXTRA_AFLAGS += -Itests/riscv/ -Itests/riscv/isa/macros/scalar

obj-y :=

obj-y += fadd.rel
AFLAGS_fadd.o += -DRVTEST_NAME="fadd_f"
obj-y += fdiv.rel
AFLAGS_fdiv.o += -DRVTEST_NAME="fdiv_f"
obj-y += fclass.rel
AFLAGS_fclass.o += -DRVTEST_NAME="fclass_f"
obj-y += fcmp.rel
AFLAGS_fcmp.o += -DRVTEST_NAME="fcmp_f"
obj-y += fcvt.rel
AFLAGS_fcvt.o += -DRVTEST_NAME="fcvt_f"
obj-y += fcvt_w.rel
AFLAGS_fcvt_w.o += -DRVTEST_NAME="fcvt_w_f"
obj-y += fmadd.rel
AFLAGS_fmadd.o += -DRVTEST_NAME="fmadd_f"
obj-y += fmin.rel
AFLAGS_fmin.o += -DRVTEST_NAME="fmin_f"
obj-y += ldst.rel
AFLAGS_ldst.o += -DRVTEST_NAME="ldst_f"
obj-y += move.rel
AFLAGS_move.o += -DRVTEST_NAME="move_f"
obj-y += recoding.rel
AFLAGS_recoding.o += -DRVTEST_NAME="recoding_f"
