obj-y :=

obj-$(CONFIG_SMMU_COMMON) += smmu_common.rel

obj-$(CONFIG_SMMU) += smmu.rel
obj-$(CONFIG_ARM_SMMU) += arm_smmu.rel
obj-$(CONFIG_ARM_SMMUv2) += arm_smmuv2.rel
obj-$(CONFIG_SMARCO_RVSMMU) += smarco_rvsmmu.rel

obj-$(CONFIG_ARM_SMMUv3) += arm_smmuv3.rel

obj-$(CONFIG_IOMMU_PGTABLE_ARMv8) += iommu_armv8.rel
obj-$(CONFIG_IOMMU_PGTABLE_RISCV) += io_pgtable.rel

obj-$(CONFIG_RISCV_IOMMU) += iommu.rel
