#include "windfu.h"

CHAR _dfu_license[] = ""
	"ZETALOG's Personal COPYRIGHT\r\n"
	"\r\n"
	"Copyright (c) 2009\r\n"
	"   ZETALOG - \"Lv ZHENG\".  All rights reserved.\r\n"
	"   Author: Lv \"Zetalog\" Zheng\r\n"
	"   Internet: zetalog@gmail.com\r\n"
	"\r\n"
	"This COPYRIGHT used to protect Personal Intelligence Rights.\r\n"
	"Redistribution and use in source and binary forms with or without\r\n"
	"modification, are permitted provided that the following conditions are\r\n"
	"met:\r\n"
	"1. Redistributions of source code must retain the above copyright\r\n"
	"   notice, this list of conditions and the following disclaimer.\r\n"
	"2. All advertising materials mentioning features or use of this software\r\n"
	"   must display the following acknowledgement:\r\n"
	"   This product includes software developed by the Lv \"Zetalog\" ZHENG.\r\n"
	"3. Neither the name of this software nor the names of its developers may\r\n"
	"   be used to endorse or promote products derived from this software\r\n"
	"   without specific prior written permission.\r\n"
	"4. Permission of redistribution and/or reuse of souce code partially only\r\n"
	"   granted to the developer(s) in the companies ZETALOG worked.\r\n"
	"5. Any modification of this software should be published to ZETALOG unless\r\n"
	"   the above copyright notice is no longer declaimed.\r\n"
	"\r\n"
	"THIS SOFTWARE IS PROVIDED BY THE ZETALOG AND CONTRIBUTORS ``AS IS'' AND\r\n"
	"ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE\r\n"
	"IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE\r\n"
	"ARE DISCLAIMED.  IN NO EVENT SHALL THE ZETALOG OR CONTRIBUTORS BE LIABLE\r\n"
	"FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL\r\n"
	"DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS\r\n"
	"OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)\r\n"
	"HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT\r\n"
	"LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY\r\n"
	"OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF\r\n"
	"SUCH DAMAGE."
	"";
