obj-y :=

obj-y += fdt_helper.rel
obj-$(CONFIG_SBI_FDT) += fdt_fixup.rel
obj-$(CONFIG_FDT_PMU) += fdt_pmu.rel
obj-$(CONFIG_RISCV_SMAIA) += fdt_irqchip_imsic.rel
obj-$(CONFIG_RISCV_SMAIA) += fdt_irqchip_aplic.rel
