# TODO: the following tests are dummy
#
# asm_test_su_c4011.S
# asm_test_su_c4021.S

EXTRA_AFLAGS += -DTESTOS
EXTRA_CFLAGS += -DTESTOS

obj-y :=

obj-y += c_raven.rel
obj-y += s_raven.rel
obj-$(CONFIG_RAVEN_IU_EXEC) += asm_test_iu_c0500.rel
obj-$(CONFIG_RAVEN_IU_EXEC) += asm_test_iu_c0501.rel
obj-$(CONFIG_RAVEN_IU_EXEC) += asm_test_iu_c0502.rel
obj-$(CONFIG_RAVEN_IU_EXEC) += asm_test_iu_c0503.rel
obj-$(CONFIG_RAVEN_IU) += asm_test_iu_c0504.rel
obj-$(CONFIG_RAVEN_IU) += asm_test_iu_c0505.rel
obj-$(CONFIG_RAVEN_IU) += asm_test_iu_c0506.rel
obj-$(CONFIG_RAVEN_IU) += asm_test_iu_c0507.rel
obj-$(CONFIG_RAVEN_IU) += asm_test_iu_c0508.rel
obj-$(CONFIG_RAVEN_IU) += asm_test_iu_c0509.rel
obj-$(CONFIG_RAVEN_IU) += asm_test_iu_c0510.rel
obj-$(CONFIG_RAVEN_IU) += asm_test_iu_c0511.rel
obj-$(CONFIG_RAVEN_IU) += asm_test_iu_c0512.rel
obj-$(CONFIG_RAVEN_IU) += asm_test_iu_c0513.rel
obj-$(CONFIG_RAVEN_IU) += asm_test_iu_c0514.rel
obj-$(CONFIG_RAVEN_IU) += asm_test_iu_c0515.rel
obj-$(CONFIG_RAVEN_IU) += asm_test_iu_c0516.rel
obj-$(CONFIG_RAVEN_IU) += asm_test_iu_c0517.rel
obj-$(CONFIG_RAVEN_IU) += asm_test_iu_c0518.rel
obj-$(CONFIG_RAVEN_IU) += asm_test_iu_c0519.rel
obj-$(CONFIG_RAVEN_IU) += asm_test_iu_c0520.rel
obj-$(CONFIG_RAVEN_IU) += asm_test_iu_c0521.rel
obj-$(CONFIG_RAVEN_IU_EXEC) += asm_test_iu_c0522.rel
obj-$(CONFIG_RAVEN_IU_EXEC) += asm_test_iu_c0523.rel
obj-$(CONFIG_RAVEN_IU_EXEC) += asm_test_iu_c0524.rel
obj-$(CONFIG_RAVEN_IU_EXEC) += asm_test_iu_c0525.rel
obj-$(CONFIG_RAVEN_IU_EXEC) += asm_test_iu_c0526.rel
obj-$(CONFIG_RAVEN_IU_EXEC) += asm_test_iu_c1000.rel
obj-$(CONFIG_RAVEN_IU_EXEC) += asm_test_iu_c1001.rel
obj-$(CONFIG_RAVEN_IU_EXEC) += asm_test_iu_c1002.rel
obj-$(CONFIG_RAVEN_IU_EXEC) += asm_test_iu_c1003.rel
obj-$(CONFIG_RAVEN_IU_EXEC) += asm_test_iu_c1004.rel
obj-$(CONFIG_RAVEN_IU_EXEC) += asm_test_iu_c1005.rel
obj-$(CONFIG_RAVEN_IU_EXEC) += asm_test_iu_c1006.rel
obj-$(CONFIG_RAVEN_IU_EXEC) += asm_test_iu_c1007.rel
obj-$(CONFIG_RAVEN_IU_EXEC) += asm_test_iu_c1008.rel
obj-$(CONFIG_RAVEN_IU_EXEC) += asm_test_iu_c1009.rel
obj-$(CONFIG_RAVEN_IU_EXEC) += asm_test_iu_c1010.rel
obj-$(CONFIG_RAVEN_IU_EXEC) += asm_test_iu_c1011.rel
obj-$(CONFIG_RAVEN_IU_EXEC) += asm_test_iu_c1012.rel
obj-$(CONFIG_RAVEN_IU_EXEC) += asm_test_iu_c1013.rel
obj-$(CONFIG_RAVEN_IU_EXEC) += asm_test_iu_c1014.rel
obj-$(CONFIG_RAVEN_IU_EXEC) += asm_test_iu_c1015.rel
obj-$(CONFIG_RAVEN_IU_EXEC) += asm_test_iu_c1016.rel
obj-$(CONFIG_RAVEN_IU_EXEC) += asm_test_iu_c1017.rel
obj-$(CONFIG_RAVEN_IU_EXEC) += asm_test_iu_c1018.rel
obj-$(CONFIG_RAVEN_IU_EXEC) += asm_test_iu_c1019.rel
obj-$(CONFIG_RAVEN_IU_EXEC) += asm_test_iu_c1020.rel
obj-$(CONFIG_RAVEN_IU_EXEC) += asm_test_iu_c1021.rel
obj-$(CONFIG_RAVEN_IU_EXEC) += asm_test_iu_c1022.rel
obj-$(CONFIG_RAVEN_IU_EXEC) += asm_test_iu_c1023.rel
obj-$(CONFIG_RAVEN_IU_EXEC) += asm_test_iu_c1024.rel
obj-$(CONFIG_RAVEN_IU_EXEC) += asm_test_iu_c1025.rel
obj-$(CONFIG_RAVEN_IU_EXEC) += asm_test_iu_c1026.rel
obj-$(CONFIG_RAVEN_IU_EXEC) += asm_test_iu_c1027.rel
obj-$(CONFIG_RAVEN_IU_EXEC) += asm_test_iu_c1028.rel
obj-$(CONFIG_RAVEN_IU_EXEC) += asm_test_iu_c1029.rel
obj-$(CONFIG_RAVEN_IU_EXEC) += asm_test_iu_c1030.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c2000.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c2001.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c2002.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c2003.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c2004.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c2005.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c2006.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c2007.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c2008.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c2009.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c2010.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c2011.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c2012.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c2013.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c2014.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c2015.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c2016.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c2017.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c2018.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c2019.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c2020.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c2021.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c2022.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c2023.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c2024.rel
obj-$(CONFIG_RAVEN_XU_SYNC) += asm_test_xu_c2100.rel
obj-$(CONFIG_RAVEN_XU_SYNC) += asm_test_xu_c2101.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c2102.rel
obj-$(CONFIG_RAVEN_XU_SYNC) += asm_test_xu_c2103.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c2600.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c2601.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c2602.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c2603.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c2604.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c2605.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c2606.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c2607.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c2608.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c2609.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c2610.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c2611.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c2612.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c2613.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c2614.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c2615.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c2616.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c2617.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c2618.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c2619.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c2620.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c2621.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c2622.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c2623.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c2624.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c3001.rel
obj-$(CONFIG_RAVEN_XU_CRC) += asm_test_xu_c3002.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c3003.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c3004.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c3005.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c3011.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c3012.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c3013.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c3014.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c3015.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c3021.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c3022.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c3023.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c3024.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c3025.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c3031.rel
obj-$(CONFIG_RAVEN_XU_SHA) += asm_test_xu_c3032.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c3033.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c3034.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c3035.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c3041.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c3042.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c3043.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c3044.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c3045.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c3051.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c3052.rel
obj-$(CONFIG_RAVEN_XU_CRC) += asm_test_xu_c3053.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c3515.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c3516.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c3517.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c3518.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c3519.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c3520.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c3521.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c3522.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c3523.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c3524.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c3525.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c3526.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c3527.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c3528.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c3529.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c3530.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c3531.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c3532.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c3533.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c3534.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c3535.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c3536.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c3537.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c3538.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c3539.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c3540.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c3541.rel
obj-$(CONFIG_RAVEN_XU) += asm_test_xu_c3542.rel
obj-$(CONFIG_RAVEN_SU_SYNC) += asm_test_su_c4010.rel
obj-$(CONFIG_RAVEN_SU) += asm_test_su_c4011.rel
obj-$(CONFIG_RAVEN_SU_SYNC) += asm_test_su_c4012.rel
obj-$(CONFIG_RAVEN_SU_SYNC) += asm_test_su_c4013.rel
obj-$(CONFIG_RAVEN_SU_SYNC) += asm_test_su_c4014.rel
obj-$(CONFIG_RAVEN_SU_SYNC) += asm_test_su_c4015.rel
obj-$(CONFIG_RAVEN_SU_SYNC) += asm_test_su_c4016.rel
obj-$(CONFIG_RAVEN_SU) += asm_test_su_c4017.rel
obj-$(CONFIG_RAVEN_SU_SYNC) += asm_test_su_c4018.rel
obj-$(CONFIG_RAVEN_SU_SYNC) += asm_test_su_c4019.rel
obj-$(CONFIG_RAVEN_SU) += asm_test_su_c4020.rel
obj-$(CONFIG_RAVEN_SU) += asm_test_su_c4021.rel
obj-$(CONFIG_RAVEN_SU_SYNC) += asm_test_su_c4022.rel
obj-$(CONFIG_RAVEN_SU_SYNC) += asm_test_su_c4023.rel
obj-$(CONFIG_RAVEN_SU_SYNC) += asm_test_su_c4024.rel
obj-$(CONFIG_RAVEN_SU_SYNC) += asm_test_su_c4025.rel
obj-$(CONFIG_RAVEN_SU_SYNC) += asm_test_su_c4026.rel
obj-$(CONFIG_RAVEN_SU_SYNC) += asm_test_su_c4027.rel
obj-$(CONFIG_RAVEN_SU_SYNC) += asm_test_su_c4028.rel
obj-$(CONFIG_RAVEN_SU_SYNC) += asm_test_su_c4029.rel
obj-$(CONFIG_RAVEN_SU_SYNC) += asm_test_su_c4030.rel
obj-$(CONFIG_RAVEN_SU_SYNC) += asm_test_su_c4031.rel
obj-$(CONFIG_RAVEN_SU_SYNC) += asm_test_su_c4032.rel
obj-$(CONFIG_RAVEN_SU_SYNC) += asm_test_su_c4033.rel
obj-$(CONFIG_RAVEN_SU_SYNC) += asm_test_su_c4034.rel
obj-$(CONFIG_RAVEN_SU_SYNC) += asm_test_su_c5005.rel
obj-$(CONFIG_RAVEN_SU_PERCPU) += asm_test_su_c5007.rel
obj-$(CONFIG_RAVEN_SU_SYNC) += asm_test_su_c5008.rel
obj-$(CONFIG_RAVEN_L2_SYNC) += asm_test_l2_c4500.rel
obj-$(CONFIG_RAVEN_L2_SYNC) += asm_test_l2_c4501.rel
obj-$(CONFIG_RAVEN_L2_SYNC) += asm_test_l2_c4502.rel
obj-$(CONFIG_RAVEN_L2_SYNC) += asm_test_l2_c4503.rel
obj-$(CONFIG_RAVEN_L2_SYNC) += asm_test_l2_c4504.rel
obj-$(CONFIG_RAVEN_L2_SYNC) += asm_test_l2_c4505.rel
obj-$(CONFIG_RAVEN_L2_SYNC) += asm_test_l2_c4506.rel
obj-$(CONFIG_RAVEN_L2_SYNC) += asm_test_l2_c4507.rel
obj-$(CONFIG_RAVEN_L2_SYNC) += asm_test_l2_c4508.rel
obj-$(CONFIG_RAVEN_L2_SYNC) += asm_test_l2_c4509.rel
obj-$(CONFIG_RAVEN_L2_SYNC) += asm_test_l2_c4510.rel
obj-$(CONFIG_RAVEN_L2_SYNC) += asm_test_l2_c4511.rel
obj-$(CONFIG_RAVEN_L2_SYNC) += asm_test_l2_c4512.rel
obj-$(CONFIG_RAVEN_L2_SYNC) += asm_test_l2_c4513.rel
obj-$(CONFIG_RAVEN_L2_SYNC) += asm_test_l2_c4514.rel
obj-$(CONFIG_RAVEN_L2_SYNC) += asm_test_l2_c4515.rel
obj-$(CONFIG_RAVEN_L2_SYNC) += asm_test_l2_c4516.rel
obj-$(CONFIG_RAVEN_L2_SYNC) += asm_test_l2_c4517.rel
obj-$(CONFIG_RAVEN_L2_SYNC) += asm_test_l2_c4518.rel
obj-$(CONFIG_RAVEN_L2_SYNC) += asm_test_l2_c4519.rel
#obj-$(CONFIG_RAVEN_L2_SYNC) += asm_test_l2_c4520.rel
obj-$(CONFIG_RAVEN_L2_SYNC) += asm_test_l2_c4521.rel
obj-$(CONFIG_RAVEN_L2_SYNC) += asm_test_l2_c4522.rel
obj-$(CONFIG_RAVEN_L2_SYNC) += asm_test_l2_c4523.rel
obj-$(CONFIG_RAVEN_L2_SYNC) += asm_test_l2_c4524.rel
#obj-$(CONFIG_RAVEN_L2_SYNC) += asm_test_l2_c4525.rel

SOURCE  = \
	raven.c \
	asm_raven.S \
	asm_test_l1_c0001.S \
	asm_test_xu_c2000.S \
	asm_test_xu_c2001.S \
	asm_test_xu_c2002.S \
	asm_test_xu_c2003.S \
	asm_test_xu_c2004.S \
	asm_test_xu_c2005.S \
	asm_test_xu_c2006.S \
	asm_test_xu_c2007.S \
	asm_test_xu_c2008.S \
	asm_test_xu_c2009.S \
	asm_test_xu_c2010.S \
	asm_test_xu_c2011.S \
	asm_test_xu_c2012.S \
	asm_test_xu_c2013.S \
	asm_test_xu_c2014.S \
	asm_test_xu_c2015.S \
	asm_test_xu_c2016.S \
	asm_test_xu_c2017.S \
	asm_test_xu_c2018.S \
	asm_test_xu_c2019.S \
	asm_test_xu_c2020.S \
	asm_test_xu_c2021.S \
	asm_test_xu_c2022.S \
	asm_test_xu_c2023.S \
	asm_test_xu_c2024.S \
	asm_test_xu_c2100.S \
	asm_test_xu_c2101.S \
	asm_test_xu_c2102.S \
	asm_test_xu_c2103.S \
	asm_test_xu_c2600.S \
	asm_test_xu_c2601.S \
	asm_test_xu_c2602.S \
	asm_test_xu_c2603.S \
	asm_test_xu_c2604.S \
	asm_test_xu_c2605.S \
	asm_test_xu_c2606.S \
	asm_test_xu_c2607.S \
	asm_test_xu_c2608.S \
	asm_test_xu_c2609.S \
	asm_test_xu_c2610.S \
	asm_test_xu_c2611.S \
	asm_test_xu_c2612.S \
	asm_test_xu_c2613.S \
	asm_test_xu_c2614.S \
	asm_test_xu_c2615.S \
	asm_test_xu_c2616.S \
	asm_test_xu_c2617.S \
	asm_test_xu_c2618.S \
	asm_test_xu_c2619.S \
	asm_test_xu_c2620.S \
	asm_test_xu_c2621.S \
	asm_test_xu_c2622.S \
	asm_test_xu_c2623.S \
	asm_test_xu_c2624.S \
	asm_test_xu_c3001.S \
	asm_test_xu_c3002.S \
	asm_test_xu_c3003.S \
	asm_test_xu_c3004.S \
	asm_test_xu_c3005.S \
	asm_test_xu_c3011.S \
	asm_test_xu_c3013.S \
	asm_test_xu_c3012.S \
	asm_test_xu_c3014.S \
	asm_test_xu_c3015.S \
	asm_test_xu_c3021.S \
	asm_test_xu_c3022.S \
	asm_test_xu_c3023.S \
	asm_test_xu_c3024.S \
	asm_test_xu_c3025.S \
	asm_test_xu_c3031.S \
	asm_test_xu_c3032.S \
	asm_test_xu_c3033.S \
	asm_test_xu_c3034.S \
	asm_test_xu_c3035.S \
	asm_test_xu_c3041.S \
	asm_test_xu_c3042.S \
	asm_test_xu_c3043.S \
	asm_test_xu_c3044.S \
	asm_test_xu_c3045.S \
	asm_test_xu_c3051.S \
	asm_test_xu_c3052.S \
	asm_test_xu_c3053.S \
	asm_test_xu_c3515.S \
	asm_test_xu_c3516.S \
	asm_test_xu_c3517.S \
	asm_test_xu_c3518.S \
	asm_test_xu_c3519.S \
	asm_test_xu_c3520.S \
	asm_test_xu_c3521.S \
	asm_test_xu_c3522.S \
	asm_test_xu_c3523.S \
	asm_test_xu_c3524.S \
	asm_test_xu_c3525.S \
	asm_test_xu_c3526.S \
	asm_test_xu_c3527.S \
	asm_test_xu_c3528.S \
	asm_test_xu_c3529.S \
	asm_test_xu_c3530.S \
	asm_test_xu_c3531.S \
	asm_test_xu_c3532.S \
	asm_test_xu_c3533.S \
	asm_test_xu_c3534.S \
	asm_test_xu_c3535.S \
	asm_test_xu_c3536.S \
	asm_test_xu_c3537.S \
	asm_test_xu_c3538.S \
	asm_test_xu_c3539.S \
	asm_test_xu_c3540.S \
	asm_test_xu_c3541.S \
	asm_test_xu_c3542.S \
	asm_test_iu_c0500.S \
	asm_test_iu_c0501.S \
	asm_test_iu_c0502.S \
	asm_test_iu_c0503.S \
	asm_test_iu_c0504.S \
	asm_test_iu_c0505.S \
	asm_test_iu_c0506.S \
	asm_test_iu_c0507.S \
	asm_test_iu_c0508.S \
	asm_test_iu_c0509.S \
	asm_test_iu_c0510.S \
	asm_test_iu_c0511.S \
	asm_test_iu_c0512.S \
	asm_test_iu_c0513.S \
	asm_test_iu_c0514.S \
	asm_test_iu_c0515.S \
	asm_test_iu_c0516.S \
	asm_test_iu_c0517.S \
	asm_test_iu_c0518.S \
	asm_test_iu_c0519.S \
	asm_test_iu_c0520.S \
	asm_test_iu_c0521.S \
	asm_test_iu_c0522.S \
	asm_test_iu_c0523.S \
	asm_test_iu_c0524.S \
	asm_test_iu_c0525.S \
	asm_test_iu_c0526.S \
	asm_test_iu_c1000.S \
	asm_test_iu_c1001.S \
	asm_test_iu_c1002.S \
	asm_test_iu_c1003.S \
	asm_test_iu_c1004.S \
	asm_test_iu_c1005.S \
	asm_test_iu_c1006.S \
	asm_test_iu_c1007.S \
	asm_test_iu_c1008.S \
	asm_test_iu_c1009.S \
	asm_test_iu_c1010.S \
	asm_test_iu_c1011.S \
	asm_test_iu_c1012.S \
	asm_test_iu_c1013.S \
	asm_test_iu_c1014.S \
	asm_test_iu_c1015.S \
	asm_test_iu_c1016.S \
	asm_test_iu_c1017.S \
	asm_test_iu_c1018.S \
	asm_test_iu_c1019.S \
	asm_test_iu_c1020.S \
	asm_test_iu_c1021.S \
	asm_test_iu_c1022.S \
	asm_test_iu_c1023.S \
	asm_test_iu_c1024.S \
	asm_test_iu_c1025.S \
	asm_test_iu_c1026.S \
	asm_test_iu_c1027.S \
	asm_test_iu_c1028.S \
	asm_test_iu_c1029.S \
	asm_test_iu_c1030.S \

#asm_test_su_c4010.S \
asm_test_su_c4011.S \
asm_test_su_c4012.S \
asm_test_su_c4013.S \
asm_test_su_c4014.S \
asm_test_su_c4015.S \
asm_test_su_c4016.S \
asm_test_su_c4017.S \
asm_test_su_c4018.S \
asm_test_su_c4019.S \
asm_test_su_c4020.S \
asm_test_su_c4021.S \
asm_test_su_c4022.S \
asm_test_su_c4023.S \
asm_test_su_c4024.S \
asm_test_su_c4025.S \
asm_test_su_c4026.S \
asm_test_su_c4027.S \
asm_test_su_c4028.S \
asm_test_su_c4029.S \
asm_test_su_c4030.S \
asm_test_su_c4031.S \
asm_test_su_c4032.S \
asm_test_su_c4033.S \
asm_test_su_c4034.S \
asm_test_su_c5005.S \
asm_test_su_c5007.S \
asm_test_su_c5008.S \
asm_test_l2_c4500.S \
asm_test_l2_c4501.S \
asm_test_l2_c4502.S \
asm_test_l2_c4503.S \
asm_test_l2_c4504.S \
asm_test_l2_c4505.S \
asm_test_l2_c4506.S \
asm_test_l2_c4507.S \
asm_test_l2_c4508.S \
asm_test_l2_c4509.S \
asm_test_l2_c4510.S \
asm_test_l2_c4511.S \
asm_test_l2_c4512.S \
asm_test_l2_c4513.S \
asm_test_l2_c4514.S \
asm_test_l2_c4515.S \
asm_test_l2_c4516.S \
asm_test_l2_c4517.S \
asm_test_l2_c4518.S \
asm_test_l2_c4519.S \
asm_test_l2_c4520.S \
asm_test_l2_c4521.S \
asm_test_l2_c4523.S \
asm_test_l2_c4522.S \
asm_test_l2_c4524.S \
asm_test_l2_c4525.S \
