obj-y :=

obj-$(CONFIG_MMC_CORE) += mmc_core.rel
obj-$(CONFIG_MMC_CORE) += card.rel
obj-$(CONFIG_MMC_SPI) += mmc_spi.rel

# Protocols
obj-$(CONFIG_MMC) += mmc.rel
obj-$(CONFIG_SD) += sd.rel
obj-$(CONFIG_SD_SPI) += sd_spi.rel

obj-$(CONFIG_SDHC) += sdhc.rel
