obj-y :=

obj-$(CONFIG_TESTS_RV64UI) += rv64ui/
obj-$(CONFIG_TESTS_RV64UM) += rv64um/
obj-$(CONFIG_TESTS_RV64UF) += rv64uf/
obj-$(CONFIG_TESTS_RV64UD) += rv64ud/
obj-$(CONFIG_TESTS_RV64UA) += rv64ua/
obj-$(CONFIG_TESTS_RV64UC) += rv64uc/
