# Copyright (C) 2008 by Lv Zheng <lv.zheng@soliton.com.cn>
#
# Licensed under the GPL v2, see the file LICENSE in this tarball.

obj-y:=

obj-y += mtd_core.rel
obj-$(CONFIG_MTD_BLOCK) += mtd_block.rel
obj-$(CONFIG_MTD_FLASH) += mtd_flash.rel
obj-$(CONFIG_MTD_DATAFLASH) += mtd_dataflash.rel
