obj-y :=

obj-$(CONFIG_QDSS) += qdss.rel
obj-$(CONFIG_QDSS_DBG) += qdss_dbg.rel
obj-$(CONFIG_QDSS_PMU) += qdss_pmu.rel
obj-$(CONFIG_QDSS_CTI) += qdss_cti.rel
obj-$(CONFIG_QDSS_TPDA) += qdss_tpda.rel
obj-$(CONFIG_QDSS_TPDM) += qdss_tpdm.rel
obj-$(CONFIG_QDSS_SWITCH_DBG) += qdss_switch_dbg.rel
obj-$(CONFIG_QDSS_SWITCH_PMU) += qdss_switch_pmu.rel
obj-$(CONFIG_QDSS_SWITCH_CFG) += qdss_switch_cfg.rel
obj-$(CONFIG_QDSS_SKITTER_CFG) += qdss_skitter_cfg.rel
