#!/bin/sh

base=httpd

sdfirm_log()
{
	echo -n "sdfirm: $@"
}

start_httpd()
{
	sdfirm_log "Configuring httpd..."
	if $base -h /home/httpd; then
		echo "[Success]" && return 0
	fi
	echo "[Failure]" && return 1
}

stop_httpd()
{
	sdfirm_log "Deconfiguring httpd..."
	pid=`pidof $base`
	if [ -n "$pid" ]; then
		kill -9 $pid
	fi
	echo "[Success]" && return 0
}

case "$1" in
	start)
		start_httpd || exit 1
		;;
	stop)
		stop_httpd || exit 1
		;;
	restart)
		stop_httpd
		start_httpd || exit 1
		;;
	*)
		echo "Usage: `basename $0` {start|stop|restart}"
		exit 1
		;;
esac
exit 0
