#!/bin/sh

cfg=/etc/network/interfaces
up=/sbin/ifup
down=/sbin/ifdown

sdfirm_log()
{
	echo -n "sdfirm: $@"
}

dump_net()
{
	ncfgs=`ifconfig | grep "inet " | awk -F ' ' '{print $2,$3}'`

	sp=0
	for n in $ncfgs; do
		adr=`echo $n | awk -F ':' '{print $2}'`
		if [ $sp -eq 0 ]; then
			echo -n "$adr "
			sp=1
		else
			echo $adr
			sp=0
		fi
	done
}

start_net()
{
	net=1

	sdfirm_log "Configuring network..."
	if [ -x $up ]; then
		$up -a >/dev/null 2>&1
		net=$?
	fi
	if [ $net -eq 0 ]; then
		echo "[Success]"
	else
		echo "[Failure]"
	fi
	echo "===== Custom Address ====="
	dump_net
	echo "=========================="
	return $net
}

stop_net()
{
	sdfirm_log "Deconfiguring network..."
	if [ -x $down ]; then
		$down -a >/dev/null 2>&1
		if [ $? -eq 0 ]; then
			echo "[Success]" && return 0
		fi
	fi
	echo "[Failure]" && return 1
}

case "$1" in
	start)
		start_net || exit 1
		;;
	stop)
		stop_net || exit 1
		;;
	restart)
		stop_net
		start_net || exit 1
		;;
	*)
		echo "Usage: `basename $0` {start|stop|restart}"
		exit 1
		;;
esac
exit 0
