#!/bin/sh

cfg=/etc/network/interfaces
up=/sbin/ifup
down=/sbin/ifdown

sdfirm_log()
{
	echo -n "sdfirm: $@"
}

start_net()
{
	sdfirm_log "Configuring network..."
	if [ -x $up ]; then
		if $up -a 1>/dev/null 2>&1; then
			echo "===== Custom Address ====="
			ifconfig eth0
			echo "=========================="
			echo "[Success]" && return 0
		fi
	fi
	echo "[Failure]" && return 1
}

stop_net()
{
	sdfirm_log "Deconfiguring network..."
	if [ -x $down ]; then
		if $down -a 1>/dev/null 2>&1; then
			echo "[Success]" && return 0
		fi
	fi
	echo "[Failure]" && return 1
}

case "$1" in
	start)
		start_net || exit 1
		;;
	stop)
		stop_net || exit 1
		;;
	restart)
		stop_net
		start_net || exit 1
		;;
	*)
		echo "Usage: `basename $0` {start|stop|restart}"
		exit 1
		;;
esac
exit 0
