#!/bin/sh

export PATH=/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin:.
export OUTPUT="/dev/null 2>&1"

ENTRY_POINT=/etc/init.d/sdfirm

check_err()
{
	if [ ! "$?" = "0" ] ; then
		disp_msg FAILURE_$1
	else
		disp_msg SUCCESS_$1
	fi
}

msg()
{
	LEVEL=$1
	MSG=$2

	echo "$MSG"
}

disp_msg()
{
	msg 1 $1
}

$ENTRY_POINT stop
