#!/bin/sh

export PATH=/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin:.
ENTRY_POINT=/etc/init.d/sdfirm

mount -t proc none /proc
# Quick test to obtain kernel boot speed
#echo -e "\nuptime: $(cut -d' ' -f1 /proc/uptime) seconds\n" >> /dev/console
mount -t sysfs none /sys
mkdir /dev/pts
mount -t devtmpfs none /dev
mount -t devpts none /dev/pts

echo "===== Factory Address ====="
echo "192.168.10.1 255.255.255.0"
echo "==========================="
if [ -e /sys/class/net/lo ]; then
	ip addr add 127.0.0.1/8 dev lo
	ip link set lo up
	route add -net 127.0.0.0/8 dev lo
fi
if [ -e /sys/class/net/eth0 ]; then
	ip addr add 192.168.10.1/24 dev eth0
	ip link set eth0 up
	# IPUPDOWN via IP
	#
	# This requires ip route plugin:
	# ip route add default via 192.168.10.254 dev eth0
	route add -net 192.168.10.0/24 dev eth0
	route add default gw 192.168.10.254
fi

# Required for running tests
if [ -f /sbin/ldconfig ]; then
	ldconfig
fi

if [ -f /etc/init.d/test_early ]; then
	/etc/init.d/test_early
fi

$ENTRY_POINT start

if [ -f /etc/init.d/test_late ]; then
	/etc/init.d/test_late
fi

#/bin/sh -i
