#!/bin/sh

# SDFIRM Embedded Linux distribution configuration
SDFIRM_STORAGING=no
SDFIRM_NETWORKING=no
SDFIRM_SYSLOG=no
if [ -e /sys/class/net/eth0 ]; then
	SDFIRM_TELNET=yes
else
	SDFIRM_TELNET=no
fi
SDFIRM_HTTP=no
SDFIRM_SILENT=no
SDFIRM_SHLIB=yes

export PATH=/bin:/sbin:/usr/bin:/usr/sbin

msg()
{
	if [ "x${SDFIRM_SYSLOG}" = "xyes" ]; then
		LEVEL=$1
		MSG=$2
	
		LOG_FACILITY=local0
		LOG_TAG=sdfirm

		if [ "$LEVEL" = "1" ] ; then
			logger -p $LOG_FACILITY.info -t $LOG_TAG $MSG
		fi
		if [ "$LEVEL" = "2" ] ; then
			logger -p $LOG_FACILITY.err -t $LOG_TAG $MSG
		fi
		if [ "$LEVEL" = "3" ] ; then
			logger -p $LOG_FACILITY.crit -t $LOG_TAG $MSG
		fi
	fi
}

disp_msg()
{
	msg 1 $1
}

check_err()
{
	if [ ! "$?" = "0" ] ; then
		msg 2 FAILURE_$1
	else
		msg 1 SUCCESS_$1
	fi
}

start_sdfirm()
{
	disp_msg BEGIN_STARTUP

	hostname `cat /etc/hostname`
	if [ "x${SDFIRM_SHLIB}" = "xyes" ]; then
	if [ -x /sbin/ldconfig ]; then
		ldconfig
	fi

	if [ "x${SDFIRM_STORAGING}" = "xyes" ]; then
		disp_msg START_DISKS
		#/etc/init.d/storaging start
		check_err DISKS
	fi

	if [ "x${SDFIRM_SYSLOG}" = "xyes" ]; then
		disp_msg START_SYSLOGD
		syslogd
		check_err SYSLOGD
	fi

	if [ "x${SDFIRM_NETWORKING}" = "xyes" ]; then
		disp_msg START_NETWORK
		/etc/init.d/networking stop
		/etc/init.d/networking start
		check_err NETWORK
	fi

	if [ "x${SDFIRM_TELNET}" = "xyes" ]; then
		disp_msg START_TELNETD
		/etc/init.d/telnetd start
		check_err TELNETD
	fi

	if [ "x${SDFIRM_HTTP}" = "xyes" ]; then
		disp_msg START_HTTPD
		/etc/init.d/httpd start
		check_err HTTPD
	fi

	disp_msg END_STARTUP

	if [ "x${SDFIRM_SILENT}" = "xyes" ]; then
		clear
	fi
}

stop_sdfirm()
{
	disp_msg BEGIN_SHUTDOWN

	if [ "x${SDFIRM_HTTP}" = "xyes" ]; then
		disp_msg STOP_HTTPD
		/etc/init.d/httpd stop
		check_err HTTPD
	fi

	if [ "x${SDFIRM_TELNET}" = "xyes" ]; then
		disp_msg STOP_TELNETD
		/etc/init.d/telnetd stop
		check_err TELNETD
	fi

	if [ "x${SDFIRM_NETWORKING}" = "xyes" ]; then
		disp_msg STOP_NETWORK
		/etc/init.d/networking stop
		check_err NETWORK
	fi

	if [ "x${SDFIRM_SYSLOG}" = "xyes" ]; then
		disp_msg STOP_SYSLOGD
		killall syslogd
		check_err SYSLOGD
	fi

	if [ "x${SDFIRM_STORAGING}" = "xyes" ]; then
		disp_msg STOP_DISKS
		#/etc/init.d/storaging stop
		check_err DISKS
	fi

	disp_msg END_SHUTDOWN
}

case "$1" in
	start)
		start_sdfirm || exit 1
		;;
	stop)
		stop_sdfirm || exit 1
		;;
	*)
		echo "Usage: `basename $0` {start|stop}"
		exit 1
		;;
esac
exit 0
