#!/bin/sh

base=telnetd

sdfirm_log()
{
	echo -n "sdfirm: $@"
}

start_telnetd()
{
	sdfirm_log "Configuring telnetd..."
	if $base; then
		echo "[Success]" && return 0
	fi
	echo "[Failure]" && return 1
}

stop_telnetd()
{
	sdfirm_log "Deconfiguring telnetd..."
	pid=`pidof $base`
	if [ -n "$pid" ]; then
		kill -9 $pid
	fi
	echo "[Success]" && return 0
}

case "$1" in
	start)
		start_telnetd || exit 1
		;;
	stop)
		stop_telnetd || exit 1
		;;
	restart)
		stop_telnetd
		start_telnetd || exit 1
		;;
	*)
		echo "Usage: `basename $0` {start|stop|restart}"
		exit 1
		;;
esac
exit 0
