
obj-y :=

obj-y += mach.rel
obj-$(CONFIG_MEM) += mem.rel
obj-y += timer.rel
#obj-y += pg.rel

obj-$(CONFIG_ARCH_HAS_IRQC) += irqc.rel
obj-$(CONFIG_UART_GEM5) += uart.rel
obj-$(CONFIG_GPIO_GEM5) += gpio.rel
obj-$(CONFIG_DDR) += ddr/
