EXTRA_CFLAGS += -DSDFIRM

obj-y += entry.rel
obj-y += mach.rel
obj-y += tsc.rel
obj-$(CONFIG_SBI) += sbi.rel
obj-$(CONFIG_MEM) += mem.rel

obj-$(CONFIG_CRCNTL) += crcntl.rel
obj-$(CONFIG_DUOWEN_TMR) += tmr.rel
obj-$(CONFIG_DUOWEN_DMA) += dma.rel
obj-$(CONFIG_DUOWEN_PCIE) += pcie_duowen.rel
