obj-y :=

obj-y += acpi_osl.rel
obj-y += acpi_core.rel
obj-y += acpi_name.rel
obj-y += acpi_utils.rel
obj-y += acpi_generic.rel
obj-y += acpi_error.rel
obj-y += acpi_table.rel
obj-y += acpi_rsdp.rel
obj-y += acpi_xsdt.rel
obj-y += acpi_fadt.rel
obj-y += acpi_fixed.rel
obj-y += acpi_event.rel
obj-y += acpi_space.rel
obj-y += acpi_parse.rel
obj-y += acpi_interp.rel

obj-$(CONFIG_ACPI_GEN) += acpi_gen.rel
