# Copyright (C) 2008 by Lv Zheng <lv.zheng@soliton.com.cn>
#
# Licensed under the GPL v2, see the file LICENSE in this tarball.

obj-y:=

obj-y += usb_scd.rel

obj-$(CONFIG_SCD_CCID) += scd_ccid.rel
obj-$(CONFIG_SCD_ICCD) += scd_iccd.rel
obj-$(CONFIG_SCD_ESC_NONE) += scd_esc_none.rel
obj-$(CONFIG_SCD_ESC_ACR122) += scd_esc_acr122.rel
