
obj-y :=

obj-y += mach.rel
obj-y += timer.rel
obj-y += pg.rel

# clock tree drivers
obj-y += clk.rel
obj-y += fabia.rel
obj-y += clk_ctl.rel
obj-y += freqplan10.rel
obj-y += freqplan11.rel
obj-y += freqplan20.rel
obj-y += agera.rel

obj-y += hmss_periph.rel
obj-y += falkor.rel
obj-y += cbf.rel

obj-$(CONFIG_QGICv2) += qgic2.rel
obj-$(CONFIG_QGICv3) += qgic3.rel
obj-$(CONFIG_UART_QUART) += quart.rel uart.rel
obj-$(CONFIG_GPIO_TLMM) += tlmm.rel
obj-$(CONFIG_RAS_IMEM) += imem.rel
obj-$(CONFIG_MONACO) += noc.rel
obj-$(CONFIG_QDSS) += qdss/
