# Copyright (C) 2008 by Lv Zheng <lv.zheng@soliton.com.cn>
#
# Licensed under the GPL v2, see the file LICENSE in this tarball.

obj-y:=

obj-y += bitops.rel
obj-y += muldiv.rel
obj-y += string.rel
obj-y += atomic.rel
obj-y += vsnprintf.rel
obj-$(CONFIG_CONSOLE_OUTPUT) += printf.rel
obj-$(CONFIG_CRC16_CCITT) += crc16_ccitt.rel
obj-$(CONFIG_CRC32) += crc32_table.rel
obj-$(CONFIG_FONTS) += font/
