EXTRA_AFLAGS += -Itests/riscv/ -Itests/riscv/isa/macros/scalar

obj-y :=

obj-y += amoadd_d.rel
AFLAGS_amoadd_d.o += -DRVTEST_NAME="amoadd_d"
obj-y += amoand_d.rel
AFLAGS_amoand_d.o += -DRVTEST_NAME="amoand_d"
obj-y += amomax_d.rel
AFLAGS_amomax_d.o += -DRVTEST_NAME="amomax_d"
obj-y += amomaxu_d.rel
AFLAGS_amomaxu_d.o += -DRVTEST_NAME="amomaxu_d"
obj-y += amomin_d.rel
AFLAGS_amomin_d.o += -DRVTEST_NAME="amomin_d"
obj-y += amominu_d.rel
AFLAGS_amominu_d.o += -DRVTEST_NAME="amominu_d"
obj-y += amoor_d.rel
AFLAGS_amoor_d.o += -DRVTEST_NAME="amoor_d"
obj-y += amoxor_d.rel
AFLAGS_amoxor_d.o += -DRVTEST_NAME="amoxor_d"
obj-y += amoswap_d.rel
AFLAGS_amoswap_d.o += -DRVTEST_NAME="amoswap_d"
obj-y += amoadd_w.rel
AFLAGS_amoadd_w.o += -DRVTEST_NAME="amoadd_w"
obj-y += amoand_w.rel
AFLAGS_amoand_w.o += -DRVTEST_NAME="amoand_w"
obj-y += amomax_w.rel
AFLAGS_amomax_w.o += -DRVTEST_NAME="amomax_w"
obj-y += amomaxu_w.rel
AFLAGS_amomaxu_w.o += -DRVTEST_NAME="amomaxu_w"
obj-y += amomin_w.rel
AFLAGS_amomin_w.o += -DRVTEST_NAME="amomin_w"
obj-y += amominu_w.rel
AFLAGS_amominu_w.o += -DRVTEST_NAME="amominu_w"
obj-y += amoor_w.rel
AFLAGS_amoor_w.o += -DRVTEST_NAME="amoor_w"
obj-y += amoxor_w.rel
AFLAGS_amoxor_w.o += -DRVTEST_NAME="amoxor_w"
obj-y += amoswap_w.rel
AFLAGS_amoswap_w.o += -DRVTEST_NAME="amoswap_w"
obj-y += lrsc.rel
AFLAGS_lrsc.o += -DRVTEST_NAME="lrsc"
