
obj-y :=

obj-y += mach.rel
obj-y += timer.rel
obj-$(CONFIG_MEM) += mem.rel
obj-$(CONFIG_CLK) += clk.rel
obj-$(CONFIG_SUNXI_CCU) += ccu.rel

obj-$(CONFIG_ARCH_HAS_IRQC) += irqc.rel
obj-$(CONFIG_UART_SUNXI) += uart.rel
obj-$(CONFIG_GPIO_SUNXI) += gpio.rel
