# Copyright (C) 2008 by Lv Zheng <lv.zheng@soliton.com.cn>
#
# Licensed under the GPL v2, see the file LICENSE in this tarball.

obj-y:=

obj-$(CONFIG_ARCH_IS_BOOT_EXE) += driver.rel

obj-y += timer/
obj-y += uart/
obj-$(CONFIG_LCD) += lcd/
obj-$(CONFIG_VIDEO) += video/
obj-$(CONFIG_MTD) += mtd/
obj-$(CONFIG_CLK) += clk/
obj-y += mmc/
obj-y += scs/
obj-$(CONFIG_GPIO) += gpio/
obj-$(CONFIG_I2C) += i2c/
obj-$(CONFIG_SPI) += spi/
obj-$(CONFIG_I3C) += i3c/
obj-$(CONFIG_DMA) += dma/
obj-$(CONFIG_PCI) += pci/
obj-$(CONFIG_RIO) += rio/
obj-$(CONFIG_IOMMU) += iommu/
obj-$(CONFIG_WDT) += wdt/
obj-y += stm/
obj-$(CONFIG_DW_UMCTL2_DDR5) += ddr/
obj-y += spd/
obj-y += noc/
obj-y += net/
obj-y += phy/
obj-y += lpc/
obj-y += espi/
obj-y += mctp/
obj-y += kcs/
obj-$(CONFIG_PERF) += pmu/
obj-$(CONFIG_RAS) += ras/
