# Copyright (C) 2008 by Lv Zheng <lv.zheng@soliton.com.cn>
#
# Licensed under the GPL v2, see the file LICENSE in this tarball.

obj-y:=

obj-y += driver.rel
obj-$(CONFIG_BLOCK) += block.o

obj-$(CONFIG_LCD) += lcd/
obj-$(CONFIG_MTD) += mtd/
obj-y += scs/
