# Copyright (C) 2008 by Lv Zheng <lv.zheng@soliton.com.cn>
#
# Licensed under the GPL v2, see the file LICENSE in this tarball.

obj-y:=

obj-y += driver.rel

obj-y += timer/
obj-y += uart/
obj-$(CONFIG_LCD) += lcd/
obj-$(CONFIG_VIDEO) += video/
obj-$(CONFIG_MTD) += mtd/
obj-$(CONFIG_CLK) += clk/
obj-y += mmc/
obj-y += scs/
obj-$(CONFIG_I2C) += i2c/
obj-$(CONFIG_SPI) += spi/
obj-$(CONFIG_DMA) += dma/
obj-$(CONFIG_PCI) += pci/
obj-$(CONFIG_IOMMU) += iommu/
obj-y += spd/
