EXTRA_AFLAGS += -Itests/riscv/ -Itests/riscv/isa/macros/scalar

obj-y :=

obj-y += div.rel
AFLAGS_div.o += -DRVTEST_NAME="div"
obj-y += divu.rel
AFLAGS_divu.o += -DRVTEST_NAME="divu"
obj-y += divuw.rel
AFLAGS_divuw.o += -DRVTEST_NAME="divuw"
obj-y += divw.rel
AFLAGS_divw.o += -DRVTEST_NAME="divw"
obj-y += mul.rel
AFLAGS_mul.o += -DRVTEST_NAME="mul"
obj-y += mulh.rel
AFLAGS_mulh.o += -DRVTEST_NAME="mulh"
obj-y += mulhsu.rel
AFLAGS_mulhsu.o += -DRVTEST_NAME="mulhsu"
obj-y += mulhu.rel
AFLAGS_mulhu.o += -DRVTEST_NAME="mulhu"
obj-y += mulw.rel
AFLAGS_mulw.o += -DRVTEST_NAME="mulw"
obj-y += rem.rel
AFLAGS_rem.o += -DRVTEST_NAME="rem"
obj-y += remu.rel
AFLAGS_remu.o += -DRVTEST_NAME="remu"
obj-y += remuw.rel
AFLAGS_remuw.o += -DRVTEST_NAME="remuw"
obj-y += remw.rel
AFLAGS_remw.o += -DRVTEST_NAME="remw"
