# Copyright (C) 2008 by Lv Zheng <lv.zheng@soliton.com.cn>
#
# Licensed under the GPL v2, see the file LICENSE in this tarball.

obj-y:=

obj-$(CONFIG_UART) += uart.rel
obj-$(CONFIG_LED) += led.rel
obj-$(CONFIG_LCD) += lcd.rel
obj-$(CONFIG_KBD) += kbd.rel
obj-$(CONFIG_SPI) += spi.rel
obj-$(CONFIG_I2C) += i2c.rel
