obj-y:

obj-$(CONFIG_MAILBOX) += mailbox.rel
obj-$(CONFIG_FDT_CPPC_RPMI) += fdt_cppc_rpmi.rel
obj-$(CONFIG_FDT_HSM_RPMI) += fdt_hsm_rpmi.rel
obj-$(CONFIG_FDT_MAILBOX_RPMI_SHMEM) += fdt_mailbox_rpmi_shmem.rel
obj-$(CONFIG_FDT_MPXY_RPMI_MBOX) += fdt_mpxy_rpmi_mbox.rel
obj-$(CONFIG_FDT_RESET_RPMI) += fdt_reset_rpmi.rel
obj-$(CONFIG_FDT_SUSPEND_RPMI) += fdt_suspend_rpmi.rel
obj-$(CONFIG_FDT_MAILBOX) += fdt_mailbox.rel
obj-$(CONFIG_FDT) += fdt_driver.rel
obj-$(CONFIG_RPMI_MAILBOX) += rpmi_mailbox.rel

obj-$(CONFIG_RAS_RPMI) += ras_rpmi_baremetal.rel
obj-$(CONFIG_MAILBOX_RPMI_SHMEM) += mailbox_rpmi_shmem_baremetal.rel
