EXTRA_AFLAGS += -Itests/riscv/ -Itests/riscv/isa/macros/scalar

obj-y :=

obj-y += fadd.rel
AFLAGS_fadd.o += -DRVTEST_NAME="fadd_d"
obj-y += fdiv.rel
AFLAGS_fdiv.o += -DRVTEST_NAME="fdiv_d"
obj-y += fclass.rel
AFLAGS_fclass.o += -DRVTEST_NAME="fclass_d"
obj-y += fcmp.rel
AFLAGS_fcmp.o += -DRVTEST_NAME="fcmp_d"
obj-y += fcvt.rel
AFLAGS_fcvt.o += -DRVTEST_NAME="fcvt_d"
obj-y += fcvt_w.rel
AFLAGS_fcvt_w.o += -DRVTEST_NAME="fcvt_w_d"
obj-y += fmadd.rel
AFLAGS_fmadd.o += -DRVTEST_NAME="fmadd_d"
obj-y += fmin.rel
AFLAGS_fmin.o += -DRVTEST_NAME="fmin_d"
obj-y += ldst.rel
AFLAGS_ldst.o += -DRVTEST_NAME="ldst_d"
obj-y += move.rel
AFLAGS_move.o += -DRVTEST_NAME="move_d"
obj-y += structural.rel
AFLAGS_structural.o += -DRVTEST_NAME="structrual_d"
obj-y += recoding.rel
AFLAGS_recoding.o += -DRVTEST_NAME="recoding_d"
