obj-y :=

obj-y += mach.rel
obj-y += mem.rel
obj-$(CONFIG_GPIO) += gpio.rel
obj-$(CONFIG_CLK) += clk.rel
obj-$(CONFIG_PRCI) += prci.rel
obj-$(CONFIG_SIFIVE_UART) += uart.rel
obj-$(CONFIG_SIFIVE_QSPI) += qspi.rel

obj-$(CONFIG_UNLEASHED_FLASH_SDCARD) += sdcard.rel
obj-$(CONFIG_UNLEASHED_FLASH_SPINOR) += spinor.rel
