
obj-y :=

obj-y += board.rel
obj-y += irq.rel
obj-y += tsc.rel
obj-y += wdt.rel

obj-$(CONFIG_GPT_AT90USB1287) += gpt.rel
obj-$(CONFIG_LED_AT90USB1287) += led.rel
obj-$(CONFIG_UART_AT90USB1287) += uart.rel
obj-$(CONFIG_SPI_AT90USB1287) += spi.rel
obj-$(CONFIG_USB_AT90USB1287) += usb.rel
obj-$(CONFIG_USB_AT90USB1287_DEV) += usb_dev.rel
