/*
 * ZETALOG's Personal COPYRIGHT
 *
 * Copyright (c) 2021
 *    ZETALOG - "Lv ZHENG".  All rights reserved.
 *    Author: Lv "Zetalog" Zheng
 *    Internet: zhenglv@hotmail.com
 *
 * This COPYRIGHT used to protect Personal Intelligence Rights.
 * Redistribution and use in source and binary forms with or without
 * modification, are permitted provided that the following conditions are
 * met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. All advertising materials mentioning features or use of this software
 *    must display the following acknowledgement:
 *    This product includes software developed by the Lv "Zetalog" ZHENG.
 * 3. Neither the name of this software nor the names of its developers may
 *    be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 * 4. Permission of redistribution and/or reuse of souce code partially only
 *    granted to the developer(s) in the companies ZETALOG worked.
 * 5. Any modification of this software should be published to ZETALOG unless
 *    the above copyright notice is no longer declaimed.
 *
 * THIS SOFTWARE IS PROVIDED BY THE ZETALOG AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE ZETALOG OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 *
 * @(#)dw_e16mp_tsmc12ffc.h: Synopsys 16G PY TSMC12FFC interface
 * $Id: dw_e16mp_tsmc12ffc.h,v 1.0 2021-12-17 16:00:00 zhenglv Exp $
 */

#ifndef __DW_E16MP_TSMC12FFC_H_INCLUDE__
#define __DW_E16MP_TSMC12FFC_H_INCLUDE__

#ifndef DW_E16MP_BASE
#define DW_E16MP_BASE(n)		(DW_E16MP##n##_BASE)
#endif
#ifndef DW_E16MP_REG
#define DW_E16MP_REG(n, offset)		(DW_E16MP_BASE(n) + ((offset) << 1))
#endif
#ifndef NR_DW_E16MPS
#define NR_DW_E16MPS		1
#endif

#define SUP_DIG_IDCODE_LO(n)			DW_E16MP_REG(n, 0x0000)
#define SUP_DIG_IDCODE_HI(n)			DW_E16MP_REG(n, 0x0001)
#define SUP_DIG_REFCLK_OVRD_IN(n)		DW_E16MP_REG(n, 0x0002)
#define SUP_DIG_MPLLA_B_DIV_CLK_OVRD_IN(n)	DW_E16MP_REG(n, 0x0003)
#define SUP_DIG_MPLLA_OVRD_IN_0(n)		DW_E16MP_REG(n, 0x0004)
#define SUP_DIG_MPLLA_OVRD_IN_1(n)		DW_E16MP_REG(n, 0x0004)
#define SUP_DIG_MPLLA_OVRD_IN_2(n)		DW_E16MP_REG(n, 0x0004)
#define SUP_DIG_MPLLA_OVRD_IN_3(n)		DW_E16MP_REG(n, 0x0004)
#define SUP_DIG_MPLLA_OVRD_IN_4(n)		DW_E16MP_REG(n, 0x0004)
#define SUP_DIG_MPLLB_OVRD_IN_1(n)		DW_E16MP_REG(n, 0x0009)
#define SUP_DIG_MPLLB_OVRD_IN_2(n)		DW_E16MP_REG(n, 0x000A)
#define SUP_DIG_MPLLB_OVRD_IN_3(n)		DW_E16MP_REG(n, 0x000B)
#define SUP_DIG_MPLLB_OVRD_IN_4(n)		DW_E16MP_REG(n, 0x000C)
#define SUP_DIG_MPLLB_OVRD_IN_0(n)		DW_E16MP_REG(n, 0x000D)
#define SUP_DIG_SUP_OVRD_IN_0(n)		DW_E16MP_REG(n, 0x000E)
#define SUP_DIG_SUP_OVRD_IN_1(n)		DW_E16MP_REG(n, 0x000F)
#define SUP_DIG_SUP_OVRD_IN_2(n)		DW_E16MP_REG(n, 0x0010)
#define SUP_DIG_SUP_OVRD_OUT(n)			DW_E16MP_REG(n, 0x0011)
#define SUP_DIG_LVL_OVRD_IN(n)			DW_E16MP_REG(n, 0x0012)
#define SUP_DIG_DEBUG(n)			DW_E16MP_REG(n, 0x0013)
#define SUP_DIG_MPLLA_ASIC_IN_0(n)		DW_E16MP_REG(n, 0x0014)
#define SUP_DIG_MPLLA_ASIC_IN_1(n)		DW_E16MP_REG(n, 0x0015)
#define SUP_DIG_MPLLA_ASIC_IN_2(n)		DW_E16MP_REG(n, 0x0016)
#define SUP_DIG_MPLLB_ASIC_IN_0(n)		DW_E16MP_REG(n, 0x0017)
#define SUP_DIG_MPLLB_ASIC_IN_1(n)		DW_E16MP_REG(n, 0x0018)
#define SUP_DIG_MPLLB_ASIC_IN_2(n)		DW_E16MP_REG(n, 0x0019)
#define SUP_DIG_MPLLA_B_DIV_CLK_ASIC_IN(n)	DW_E16MP_REG(n, 0x001A)
#define SUP_DIG_ASIC_IN(n)			DW_E16MP_REG(n, 0x001B)
#define SUP_DIG_LVL_ASIC_IN(n)			DW_E16MP_REG(n, 0x001C)
#define SUP_DIG_SUP_OVRD_MISC(n)		DW_E16MP_REG(n, 0x001D)
#define SUP_DIG_MPLLA_FREQ_CNT_INIT_ASIC_IN(n)	DW_E16MP_REG(n, 0x001E)
#define SUP_DIG_MPLLB_FREQ_CNT_INIT_ASIC_IN(n)	DW_E16MP_REG(n, 0x001F)
#define SUP_DIG_MPLLA_MPLL_PWR_CTL_CAL_CTRL(n)	DW_E16MP_REG(n, 0x0020)
#define SUP_DIG_MPLLA_MPLL_PWR_CTL_MPLL_OVRD(n)	DW_E16MP_REG(n, 0x0021)
#define SUP_DIG_MPLLA_MPLL_PWR_CTL_STAT(n)	DW_E16MP_REG(n, 0x0022)
#define SUP_DIG_MPLLA_MPLL_PWR_CTL_MPLL_MISC_TIME_THRESHOLD(n)		\
	DW_E16MP_REG(n, 0x0023)
#define SUP_DIG_MPLLA_MPLL_PWR_CTL_PCLK_EN_AND_VCO_CLK_STABILIZATION_TIME_THRESHOLD(n)		\
	DW_E16MP_REG(n, 0x0024)
#define SUP_DIG_MPLLA_MPLL_PWR_CTL_PCLK_DIS_AND_MPLL_VCO_PWRDN_THRESH(n)\
	DW_E16MP_REG(n, 0x0025)
#define SUP_DIG_MPLLA_MPLL_PWR_CTL_MPLL_ANA_PWRUP_TIME_THRESH(n)	\
	DW_E16MP_REG(n, 0x0026)
#define SUP_DIG_MPLLA_MPLL_PWR_CTL_MPLL_FBCLK_EN_AND_MPLL_FBDIGCLK_DIS_TIME_THRESHOLD(n)	\
	DW_E16MP_REG(n, 0x0027)
#define SUP_DIG_MPLLA_MPLL_PWR_CTL_MPLL_COARSE_TUNE_VAL(n)		\
	DW_E16MP_REG(n, 0x0028)
#define SUP_DIG_MPLLA_MPLL_PWR_CTL_MPLL_SKIPCAL_COARSE_TUNE(n)		\
	DW_E16MP_REG(n, 0x0029)
#define SUP_DIG_MPLLA_SSC_SS_PHASE(n)		DW_E16MP_REG(n, 0x002A)
#define SUP_DIG_MPLLA_SSC_SS_FREQ_0(n)		DW_E16MP_REG(n, 0x002B)
#define SUP_DIG_MPLLA_SSC_SS_FREQ_1(n)		DW_E16MP_REG(n, 0x002C)
#define SUP_DIG_MPLLB_MPLL_PWR_CTL_CAL_CTRL(n)	DW_E16MP_REG(n, 0x002D)
#define SUP_DIG_MPLLB_MPLL_PWR_CTL_MPLL_OVRD(n)	DW_E16MP_REG(n, 0x002E)
#define SUP_DIG_MPLLB_MPLL_PWR_CTL_STAT(n)	DW_E16MP_REG(n, 0x002F)
#define SUP_DIG_MPLLB_MPLL_PWR_CTL_MPLL_MISC_TIME_THRESHOLD(n)		\
	DW_E16MP_REG(n, 0x0030)
#define SUP_DIG_MPLLB_MPLL_PWR_CTL_PCLK_EN_AND_VCO_CLK_STABILIZATION_TIME_THRESHOLD(n)		\
	DW_E16MP_REG(n, 0x0031)
#define SUP_DIG_MPLLB_MPLL_PWR_CTL_PCLK_DIS_AND_MPLL_VCO_PWRDN_THRESH(n)\
	DW_E16MP_REG(n, 0x0032)
#define SUP_DIG_MPLLB_MPLL_PWR_CTL_MPLL_ANA_PWRUP_TIME_THRESH(n)	\
	DW_E16MP_REG(n, 0x0033)
#define SUP_DIG_MPLLB_MPLL_PWR_CTL_MPLL_FBCLK_EN_AND_MPLL_FBDIGCLK_DIS_TIME_THRESHOLD(n)	\
	DW_E16MP_REG(n, 0x0034)
#define SUP_DIG_MPLLB_MPLL_PWR_CTL_MPLL_COARSE_TUNE_VAL(n)		\
	DW_E16MP_REG(n, 0x0035)
#define SUP_DIG_MPLLB_MPLL_PWR_CTL_MPLL_SKIPCAL_COARSE_TUNE(n)		\
	DW_E16MP_REG(n, 0x0036)
#define SUP_DIG_MPLLB_SSC_SS_PHASE(n)		DW_E16MP_REG(n, 0x0037)
#define SUP_DIG_MPLLB_SSC_SS_FREQ_0(n)		DW_E16MP_REG(n, 0x0038)
#define SUP_DIG_MPLLB_SSC_SS_FREQ_1(n)		DW_E16MP_REG(n, 0x0039)
#define SUP_DIG_CLK_RST_BG_PWRUP_TIME_0(n)	DW_E16MP_REG(n, 0x003A)
#define SUP_DIG_CLK_RST_BG_PWRUP_TIME_1(n)	DW_E16MP_REG(n, 0x003B)
#define SUP_ANA_MPLLA_LOOP_CTRL(n)		DW_E16MP_REG(n, 0x0040)
#define SUP_ANA_MPLLA_OVRD(n)			DW_E16MP_REG(n, 0x0041)
#define SUP_ANA_MPLLA_ATB1(n)			DW_E16MP_REG(n, 0x0042)
#define SUP_ANA_MPLLA_ATB2(n)			DW_E16MP_REG(n, 0x0043)
#define SUP_ANA_MPLLA_ATB3(n)			DW_E16MP_REG(n, 0x0044)
#define SUP_ANA_MPLLB_LOOP_CTRL(n)		DW_E16MP_REG(n, 0x0045)
#define SUP_ANA_MPLLB_OVRD(n)			DW_E16MP_REG(n, 0x0046)
#define SUP_ANA_MPLLB_ATB1(n)			DW_E16MP_REG(n, 0x0047)
#define SUP_ANA_MPLLB_ATB2(n)			DW_E16MP_REG(n, 0x0048)
#define SUP_ANA_MPLLB_ATB3(n)			DW_E16MP_REG(n, 0x0049)
#define SUP_ANA_RTUNE_CTRL(n)			DW_E16MP_REG(n, 0x004A)
#define SUP_ANA_SWITCH_PWR_MEAS(n)		DW_E16MP_REG(n, 0x004B)
#define SUP_ANA_SWITCH_MISC_MEAS(n)		DW_E16MP_REG(n, 0x004C)
#define SUP_ANA_BG(n)				DW_E16MP_REG(n, 0x004D)
#define SUP_DIG_RTUNE_DEBUG(n)			DW_E16MP_REG(n, 0x0060)
#define SUP_DIG_RTUNE_CONFIG(n)			DW_E16MP_REG(n, 0x0061)
#define SUP_DIG_RTUNE_STAT(n)			DW_E16MP_REG(n, 0x0062)
#define SUP_DIG_RTUNE_RX_SET_VAL(n)		DW_E16MP_REG(n, 0x0063)
#define SUP_DIG_RTUNE_TXDN_SET_VAL(n)		DW_E16MP_REG(n, 0x0064)
#define SUP_DIG_RTUNE_TXUP_SET_VAL(n)		DW_E16MP_REG(n, 0x0065)
#define SUP_DIG_RTUNE_RX_STAT(n)		DW_E16MP_REG(n, 0x0066)
#define SUP_DIG_RTUNE_TXDN_STAT(n)		DW_E16MP_REG(n, 0x0067)
#define SUP_DIG_RTUNE_TXUP_STAT(n)		DW_E16MP_REG(n, 0x0068)
#define SUP_DIG_ANA_MPLLA_OVRD_OUT(n)		DW_E16MP_REG(n, 0x0080)
#define SUP_DIG_ANA_MPLLB_OVRD_OUT(n)		DW_E16MP_REG(n, 0x0081)
#define SUP_DIG_ANA_RTUNE_OVRD_OUT(n)		DW_E16MP_REG(n, 0x0082)
#define SUP_DIG_ANA_RX_TERM_OVRD_OUT(n)		DW_E16MP_REG(n, 0x0083)
#define SUP_DIG_ANA_STAT(n)			DW_E16MP_REG(n, 0x0084)
#define SUP_DIG_ANA_BG_OVRD_OUT(n)		DW_E16MP_REG(n, 0x0085)
#define SUP_DIG_ANA_MPLLA_PMIX_OVRD_OUT(n)	DW_E16MP_REG(n, 0x0086)
#define SUP_DIG_ANA_MPLLB_PMIX_OVRD_OUT(n)	DW_E16MP_REG(n, 0x0087)
#define SUP_DIG_FREQ_CNT_PEAK_ASIC_IN(n)	DW_E16MP_REG(n, 0x00A0)
#define SUP_DIG_TXUP_TERM_OFFSET_ASIC_IN(n)	DW_E16MP_REG(n, 0x00A1)
#define SUP_DIG_TXDN_TERM_OFFSET_ASIC_IN(n)	DW_E16MP_REG(n, 0x00A2)
#define SUP_DIG_MISC_ASIC_IN(n)			DW_E16MP_REG(n, 0x00A3)

/* LANE registers */
#define DW_E16MP_LREG(n, l, offset)		\
	DW_E16MP_REG(n, (offset) + ((l) << 8))
#define LANE_DIG_ASIC_LANE_OVRD_IN(n, l)	DW_E16MP_LREG(n, l, 0x1000)
#define LANE_DIG_ASIC_TX_OVRD_IN_0(n, l)	DW_E16MP_LREG(n, l, 0x1001)
#define LANE_DIG_ASIC_TX_OVRD_IN_1(n, l)	DW_E16MP_LREG(n, l, 0x1002)
#define LANE_DIG_ASIC_TX_OVRD_IN_2(n, l)	DW_E16MP_LREG(n, l, 0x1003)
#define LANE_DIG_ASIC_TX_OVRD_OUT(n, l)		DW_E16MP_LREG(n, l, 0x1004)
#define LANE_DIG_ASIC_RX_OVRD_IN_0(n, l)	DW_E16MP_LREG(n, l, 0x1005)
#define LANE_DIG_ASIC_RX_OVRD_IN_1(n, l)	DW_E16MP_LREG(n, l, 0x1006)
#define LANE_DIG_ASIC_RX_OVRD_IN_2(n, l)	DW_E16MP_LREG(n, l, 0x1007)
#define LANE_DIG_ASIC_RX_OVRD_IN_3(n, l)	DW_E16MP_LREG(n, l, 0x1008)
#define LANE_DIG_ASIC_RX_OVRD_EQ_IN_0(n, l)	DW_E16MP_LREG(n, l, 0x1009)
#define LANE_DIG_ASIC_RX_OVRD_EQ_IN_1(n, l)	DW_E16MP_LREG(n, l, 0x100A)
#define LANE_DIG_ASIC_RX_OVRD_OUT_0(n, l)	DW_E16MP_LREG(n, l, 0x100B)
#define LANE_DIG_ASIC_LANE_ASIC_IN(n, l)	DW_E16MP_LREG(n, l, 0x100C)
#define LANE_DIG_ASIC_TX_ASIC_IN_0(n, l)	DW_E16MP_LREG(n, l, 0x100D)
#define LANE_DIG_ASIC_TX_ASIC_IN_1(n, l)	DW_E16MP_LREG(n, l, 0x100E)
#define LANE_DIG_ASIC_TX_ASIC_IN_2(n, l)	DW_E16MP_LREG(n, l, 0x100F)
#define LANE_DIG_ASIC_TX_ASIC_OUT(n, l)		DW_E16MP_LREG(n, l, 0x1010)
#define LANE_DIG_ASIC_RX_ASIC_IN_0(n, l)	DW_E16MP_LREG(n, l, 0x1011)
#define LANE_DIG_ASIC_RX_ASIC_IN_1(n, l)	DW_E16MP_LREG(n, l, 0x1012)
#define LANE_DIG_ASIC_RX_EQ_ASIC_IN_0(n, l)	DW_E16MP_LREG(n, l, 0x1013)
#define LANE_DIG_ASIC_RX_EQ_ASIC_IN_1(n, l)	DW_E16MP_LREG(n, l, 0x1014)
#define LANE_DIG_ASIC_RX_CDR_VCO_ASIC_IN_0(n, l)	\
	DW_E16MP_LREG(n, l, 0x1015)
#define LANE_DIG_ASIC_RX_CDR_VCO_ASIC_IN_1(n, l)	\
	DW_E16MP_LREG(n, l, 0x1016)
#define LANE_DIG_ASIC_RX_ASIC_OUT_0(n, l)	DW_E16MP_LREG(n, l, 0x1017)
#define LANE_DIG_ASIC_RX_OVRD_EQ_IN_2(n, l)	DW_E16MP_LREG(n, l, 0x1018)
#define LANE_DIG_ASIC_RX_OVRD_EQ_IN_3(n, l)	DW_E16MP_LREG(n, l, 0x1019)
#define LANE_DIG_ASIC_TX_OVRD_MISC(n, l)	DW_E16MP_LREG(n, l, 0x101A)
#define LANE_DIG_ASIC_RX_OVRD_MISC(n, l)	DW_E16MP_LREG(n, l, 0x101B)
#define LANE_DIG_TX_PWRCTL_TX_PSTATE_P0(n, l)	DW_E16MP_LREG(n, l, 0x1020)
#define LANE_DIG_TX_PWRCTL_TX_PSTATE_P0S(n, l)	DW_E16MP_LREG(n, l, 0x1021)
#define LANE_DIG_TX_PWRCTL_TX_PSTATE_P1(n, l)	DW_E16MP_LREG(n, l, 0x1022)
#define LANE_DIG_TX_PWRCTL_TX_PSTATE_P2(n, l)	DW_E16MP_LREG(n, l, 0x1023)
#define LANE_DIG_TX_PWRCTL_TX_PWRUP_TIME_0(n, l)	\
	DW_E16MP_LREG(n, l, 0x1024)
#define LANE_DIG_TX_PWRCTL_TX_PWRUP_TIME_1(n, l)	\
	DW_E16MP_LREG(n, l, 0x1025)
#define LANE_DIG_TX_PWRCTL_TX_PWRUP_TIME_2(n, l)	\
	DW_E16MP_LREG(n, l, 0x1026)
#define LANE_DIG_TX_PWRCTL_TX_PWRUP_TIME_3(n, l)	\
	DW_E16MP_LREG(n, l, 0x1027)
#define LANE_DIG_TX_PWRCTL_TX_PWRUP_TIME_4(n, l)	\
	DW_E16MP_LREG(n, l, 0x1028)
#define LANE_DIG_TX_PWRCTL_TX_FIFO_BYPASS(n, l)	DW_E16MP_LREG(n, l, 0x1029)
#define LANE_DIG_TX_PWRCTL_TX_PWRUP_TIME_5(n, l)	\
	DW_E16MP_LREG(n, l, 0x102A)
#define LANE_DIG_TX_LBERT_CTL(n, l)		DW_E16MP_LREG(n, l, 0x102B)
#define LANE_DIG_RX_PWRCTL_RX_PSTATE_P0(n, l)	DW_E16MP_LREG(n, l, 0x1040)
#define LANE_DIG_RX_PWRCTL_RX_PSTATE_P0S(n, l)	DW_E16MP_LREG(n, l, 0x1041)
#define LANE_DIG_RX_PWRCTL_RX_PSTATE_P1(n, l)	DW_E16MP_LREG(n, l, 0x1042)
#define LANE_DIG_RX_PWRCTL_RX_PSTATE_P2(n, l)	DW_E16MP_LREG(n, l, 0x1043)
#define LANE_DIG_RX_PWRCTL_RX_PWRUP_TIME_0(n, l)	\
	DW_E16MP_LREG(n, l, 0x1044)
#define LANE_DIG_RX_PWRCTL_RX_PWRUP_TIME_1(n, l)	\
	DW_E16MP_LREG(n, l, 0x1045)
#define LANE_DIG_RX_PWRCTL_RX_PWRUP_TIME_2(n, l)	\
	DW_E16MP_LREG(n, l, 0x1046)
#define LANE_DIG_RX_PWRCTL_RX_PWRUP_TIME_3(n, l)	\
	DW_E16MP_LREG(n, l, 0x1047)
#define LANE_DIG_RX_VCOCAL_RX_VCO_CAL_CTRL_0(n, l)	\
	DW_E16MP_LREG(n, l, 0x1048)
#define LANE_DIG_RX_VCOCAL_RX_VCO_CAL_CTRL_1(n, l)	\
	DW_E16MP_LREG(n, l, 0x1049)
#define LANE_DIG_RX_VCOCAL_RX_VCO_CAL_CTRL_2(n, l)	\
	DW_E16MP_LREG(n, l, 0x104A)
#define LANE_DIG_RX_VCOCAL_RX_VCO_CAL_TIME_0(n, l)	\
	DW_E16MP_LREG(n, l, 0x104B)
#define LANE_DIG_RX_VCOCAL_RX_VCO_CAL_TIME_1(n, l)	\
	DW_E16MP_LREG(n, l, 0x104C)
#define LANE_DIG_RX_VCOCAL_RX_VCO_STAT_0(n, l)	DW_E16MP_LREG(n, l, 0x104D)
#define LANE_DIG_RX_VCOCAL_RX_VCO_STAT_1(n, l)	DW_E16MP_LREG(n, l, 0x104E)
#define LANE_DIG_RX_VCOCAL_RX_VCO_STAT_2(n, l)	DW_E16MP_LREG(n, l, 0x104F)
#define LANE_DIG_RX_RX_ALIGN_XAUI_COMM_MASK(n, l)	\
	DW_E16MP_LREG(n, l, 0x1050)
#define LANE_DIG_RX_LBERT_CTL(n, l)		DW_E16MP_LREG(n, l, 0x1051)
#define LANE_DIG_RX_LBERT_ERR(n, l)		DW_E16MP_LREG(n, l, 0x1052)
#define LANE_DIG_RX_CDR_CDR_CTL_0(n, l)		DW_E16MP_LREG(n, l, 0x1053)
#define LANE_DIG_RX_CDR_CDR_CTL_1(n, l)		DW_E16MP_LREG(n, l, 0x1054)
#define LANE_DIG_RX_CDR_CDR_CTL_2(n, l)		DW_E16MP_LREG(n, l, 0x1055)
#define LANE_DIG_RX_CDR_CDR_CTL_3(n, l)		DW_E16MP_LREG(n, l, 0x1056)
#define LANE_DIG_RX_CDR_CDR_CTL_4(n, l)		DW_E16MP_LREG(n, l, 0x1057)
#define LANE_DIG_RX_CDR_STAT(n, l)		DW_E16MP_LREG(n, l, 0x1058)
#define LANE_DIG_RX_DPLL_FREQ(n, l)		DW_E16MP_LREG(n, l, 0x1059)
#define LANE_DIG_RX_DPLL_FREQ_BOUND_0(n, l)	DW_E16MP_LREG(n, l, 0x105A)
#define LANE_DIG_RX_DPLL_FREQ_BOUND_1(n, l)	DW_E16MP_LREG(n, l, 0x105B)
#define LANE_DIG_RX_ADPTCTL_ADPT_CFG_0(n, l)	DW_E16MP_LREG(n, l, 0x1060)
#define LANE_DIG_RX_ADPTCTL_ADPT_CFG_1(n, l)	DW_E16MP_LREG(n, l, 0x1061)
#define LANE_DIG_RX_ADPTCTL_ADPT_CFG_2(n, l)	DW_E16MP_LREG(n, l, 0x1062)
#define LANE_DIG_RX_ADPTCTL_ADPT_CFG_3(n, l)	DW_E16MP_LREG(n, l, 0x1063)
#define LANE_DIG_RX_ADPTCTL_ADPT_CFG_4(n, l)	DW_E16MP_LREG(n, l, 0x1064)
#define LANE_DIG_RX_ADPTCTL_ADPT_CFG_5(n, l)	DW_E16MP_LREG(n, l, 0x1065)
#define LANE_DIG_RX_ADPTCTL_ADPT_CFG_6(n, l)	DW_E16MP_LREG(n, l, 0x1066)
#define LANE_DIG_RX_ADPTCTL_ADPT_CFG_7(n, l)	DW_E16MP_LREG(n, l, 0x1067)
#define LANE_DIG_RX_ADPTCTL_ADPT_CFG_8(n, l)	DW_E16MP_LREG(n, l, 0x1068)
#define LANE_DIG_RX_ADPTCTL_ADPT_CFG_9(n, l)	DW_E16MP_LREG(n, l, 0x1069)
#define LANE_DIG_RX_ADPTCTL_RST_ADPT_CFG(n, l)	DW_E16MP_LREG(n, l, 0x106A)
#define LANE_DIG_RX_ADPTCTL_ATT_STATUS(n, l)	DW_E16MP_LREG(n, l, 0x106B)
#define LANE_DIG_RX_ADPTCTL_VGA_STATUS(n, l)	DW_E16MP_LREG(n, l, 0x106C)
#define LANE_DIG_RX_ADPTCTL_CTLE_STATUS(n, l)	DW_E16MP_LREG(n, l, 0x106D)
#define LANE_DIG_RX_ADPTCTL_DFE_TAP1_STATUS(n, l)	\
	DW_E16MP_LREG(n, l, 0x106E)
#define LANE_DIG_RX_ADPTCTL_DFE_TAP2_STATUS(n, l)	\
	DW_E16MP_LREG(n, l, 0x106F)

void dw_e16mp_tsmc12ffc_init(int n);

#endif /* __DW_E16MP_TSMC12FFC_H_INCLUDE__ */
