/* Reference,  https, //spacemit.feishu.cn/wiki/I5OBwa11Ei7Ycrk5QdMcEvrdndg */

#ifndef __SPACEMIT_LPC_H_INCLUDE__
#define __SPACEMIT_LPC_H_INCLUDE__

#ifndef SPACEMIT_LPC_BASE
#define SPACEMIT_LPC_BASE(n)		(SPACEMIT_LPC##n##_BASE)
#endif
#ifndef SPACEMIT_LPC_REG
#define SPACEMIT_LPC_REG(n, offset)	(SPACEMIT_LPC_BASE(n) + (offset))
#endif

/* Register offset */
#define LPC_CFG(n)			SPACEMIT_LPC_REG(n, 0x00)
#define LPC_CMD_OP(n)			SPACEMIT_LPC_REG(n, 0x04)
#define LPC_STATUS(n)			SPACEMIT_LPC_REG(n, 0x08)
#define LPC_INT_MASK(n)			SPACEMIT_LPC_REG(n, 0x0c)
#define LPC_INT_STATUS(n)		SPACEMIT_LPC_REG(n, 0x10)
#define LPC_INT_RAW_STATUS(n)		SPACEMIT_LPC_REG(n, 0x14)
#define LPC_INT_CLR(n)			SPACEMIT_LPC_REG(n, 0x18)
#define LPC_WAIT_COUNT(n)		SPACEMIT_LPC_REG(n, 0x1c)
#define LPC_ADDR(n)			SPACEMIT_LPC_REG(n, 0x20)
#define LPC_WDATA(n)			SPACEMIT_LPC_REG(n, 0x24)
#define LPC_RDATA(n)			SPACEMIT_LPC_REG(n, 0x28)
#define LPC_DEBUG(n)			SPACEMIT_LPC_REG(n, 0x2c)
#define SERIRQ_CFG(n)			SPACEMIT_LPC_REG(n, 0x30)
#define SERIRQ_OP(n)			SPACEMIT_LPC_REG(n, 0x34)
#define SERIRQ_SLOT_MASK(n)		SPACEMIT_LPC_REG(n, 0x38)
#define SERIRQ_SLOT_IRQ(n)		SPACEMIT_LPC_REG(n, 0x3c)
#define SERIRQ_SLOT_CLR(n)		SPACEMIT_LPC_REG(n, 0x40)
#define SERIRQ_DEBUG(n)			SPACEMIT_LPC_REG(n, 0x44)
#define LPC_MEM_CFG(n)			SPACEMIT_LPC_REG(n, 0x50)

/* 8.1 LPC_CFG */
#define LPC_CFG_SERIRQ_EN		_BV(16)
#define LPC_CFG_LONG_WAIT_EN		_BV(12)
#define LPC_CFG_FW_BYTE_LEN		GENMASK(9, 8)
#define LPC_CFG_CYCLE_TYPE		GENMASK(5, 4)
#define LPC_CFG_LFRAME_WIDE		GENMASK(1, 0)

/* 8.2 LPC_CMD_OP */
#define LPC_CMD_OP			_BV(0)

/* 8.3 LPC_STATUS */
#define LPC_STATUS_SERIRQ_BUSY		_BV(4)
#define LPC_STATUS_LPC_BUSY		_BV(0)

/* 8.4 LPC_INT_MASK */
#define LPC_INT_SYNC_ERR_MASK		_BV(24)
#define LPC_INT_NO_SYNC_MASK		_BV(20)
#define LPC_INT_LWAIT_TIMEOUT_MASK	_BV(16)
#define LPC_INT_SWAIT_TIMEOUT_MASK	_BV(12)
#define LPC_INT_SERIRQ_INT_MASK		_BV(8)
#define LPC_INT_SERIRQ_DONE_MASK	_BV(4)
#define LPC_INT_OP_DONE_MASK		_BV(0)

/* 8.5 LPC_INT_STATUS */
#define LPC_INT_STATUS_SYNC_ERR		_BV(24)
#define LPC_INT_STATUS_NO_SYNC		_BV(20)
#define LPC_INT_STATUS_LWAIT_TIMEOUT	_BV(16)
#define LPC_INT_STATUS_SWAIT_TIMEOUT	_BV(12)
#define LPC_INT_STATUS_SERIRQ_INT	_BV(8)
#define LPC_INT_STATUS_SERIRQ_DONE	_BV(4)
#define LPC_INT_STATUS_OP_DONE		_BV(0)

/* 8.6 LPC_INT_RAW_STATUS */
#define LPC_INT_RAW_STATUS_SYNCEER	_BV(24)
#define LPC_INT_RAW_STATUS_NO_SYNC	_BV(20)
#define LPC_INT_RAW_STATUS_LWAIT_TIMEOUT	_BV(16)
#define LPC_INT_RAW_STATUS_SWAIT_TIMEOUT	_BV(12)
#define LPC_INT_RAW_STATUS_SERIRQ_INT	_BV(8)
#define LPC_INT_RAW_STATUS_SERIRQ_DONE	_BV(4)
#define LPC_INT_RAW_STATUS_OP_DONE	_BV(0)

/* 8.7 LPC_INT_CLR */
#define LPC_INT_SYNCERR_CLR		_BV(24)
#define LPC_INT_NO_SYNC_CLR		_BV(20)
#define LPC_INT_LWAIT_TIMEOUT_CLR	_BV(16)
#define LPC_INT_SWAIT_TIMEOUT_CLR	_BV(12)
#define LPC_INT_SERIRQ_DONE_CLR		_BV(4)
#define LPC_INT_OP_DONE_CLR		_BV(0)

/* 8.8 LPC_WAIT_COUNT */
#define LPC_WAIT_ABORT_COUNT		GENMASK(27, 24)
#define LPC_WAIT_SWAIT_COUNT		GENMASK(23, 20)
#define LPC_WAIT_LWAIT_COUNT		GENMASK(15, 0)

/* 8.9 LPC_ADDR */
#define LPC_ADDR			GENMASK(31, 0)

/* 8.10 LPC_WDATA */
#define LPC_WDATA			GENMASK(31, 0)

/* 8.11 LPC_RDATA */
#define LPC_RDATA			GENMASK(31, 0)

/* 8.12 LPC_DEBUG */
#define LPC_DEBUG_LAD_I			GENMASK(31, 28)
#define LPC_DEBUG_LPC_COUNT		GENMASK(27, 24)
#define LPC_DEBUG_LPC_SYNC_COUNT	GENMASK(23, 8)
#define LPC_DEBUG_LPC_FSM		GENMASK(5, 0)

/* 8.13 SEIRQ_CFG */
#define SEIRQ_CFG_SERIRQ_NUM		GENMASK(15, 12)
#define SEIRQ_CFG_SERIRQ_IDLE_WIDE	GENMASK(9, 8)
#define SEIRQ_CFG_SERIRQ_START_WIDE	GENMASK(5, 4)
#define SEIRQ_CFG_SERIRQ_MODE		_BV(0)

/* 8.14 SERIRQ_OP */
#define SERIRQ_OP			_BV(0)

/* 8.15 SERIRQ_SLOT_MASK */
#define SERIRQ_SLOT_MASK31		_BV(31)
#define SERIRQ_SLOT_MASK30		_BV(30)
#define SERIRQ_SLOT_MASK29		_BV(29)
#define SERIRQ_SLOT_MASK28		_BV(28)
#define SERIRQ_SLOT_MASK27		_BV(27)
#define SERIRQ_SLOT_MASK26		_BV(26)
#define SERIRQ_SLOT_MASK25		_BV(25)
#define SERIRQ_SLOT_MASK24		_BV(24)
#define SERIRQ_SLOT_MASK23		_BV(23)
#define SERIRQ_SLOT_MASK22		_BV(22)
#define SERIRQ_SLOT_MASK21		_BV(21)
#define SERIRQ_SLOT_MASK20		_BV(20)
#define SERIRQ_SLOT_MASK19		_BV(19)
#define SERIRQ_SLOT_MASK18		_BV(18)
#define SERIRQ_SLOT_MASK17		_BV(17)
#define SERIRQ_SLOT_MASK16		_BV(16)
#define SERIRQ_SLOT_MASK15		_BV(15)
#define SERIRQ_SLOT_MASK14		_BV(14)
#define SERIRQ_SLOT_MASK13		_BV(13)
#define SERIRQ_SLOT_MASK12		_BV(12)
#define SERIRQ_SLOT_MASK11		_BV(11)
#define SERIRQ_SLOT_MASK10		_BV(10)
#define SERIRQ_SLOT_MASK9		_BV(9)
#define SERIRQ_SLOT_MASK8		_BV(8)
#define SERIRQ_SLOT_MASK7		_BV(7)
#define SERIRQ_SLOT_MASK6		_BV(6)
#define SERIRQ_SLOT_MASK5		_BV(5)
#define SERIRQ_SLOT_MASK4		_BV(4)
#define SERIRQ_SLOT_MASK3		_BV(3)
#define SERIRQ_SLOT_MASK2		_BV(2)
#define SERIRQ_SLOT_MASK1		_BV(1)
#define SERIRQ_SLOT_MASK0		_BV(0)

/* 8.16 SERIRQ_SLOT_IRQ */
#define SERIRQ_SLOT_IRQ31		_BV(31)
#define SERIRQ_SLOT_IRQ30		_BV(30)
#define SERIRQ_SLOT_IRQ29		_BV(29)
#define SERIRQ_SLOT_IRQ28		_BV(28)
#define SERIRQ_SLOT_IRQ27		_BV(27)
#define SERIRQ_SLOT_IRQ26		_BV(26)
#define SERIRQ_SLOT_IRQ25		_BV(25)
#define SERIRQ_SLOT_IRQ24		_BV(24)
#define SERIRQ_SLOT_IRQ23		_BV(23)
#define SERIRQ_SLOT_IRQ22		_BV(22)
#define SERIRQ_SLOT_IRQ21		_BV(21)
#define SERIRQ_SLOT_IRQ20		_BV(20)
#define SERIRQ_SLOT_IRQ19		_BV(19)
#define SERIRQ_SLOT_IRQ18		_BV(18)
#define SERIRQ_SLOT_IRQ17		_BV(17)
#define SERIRQ_SLOT_IRQ16		_BV(16)
#define SERIRQ_SLOT_IRQ15		_BV(15)
#define SERIRQ_SLOT_IRQ14		_BV(14)
#define SERIRQ_SLOT_IRQ13		_BV(13)
#define SERIRQ_SLOT_IRQ12		_BV(12)
#define SERIRQ_SLOT_IRQ11		_BV(11)
#define SERIRQ_SLOT_IRQ10		_BV(10)
#define SERIRQ_SLOT_IRQ9		_BV(9)
#define SERIRQ_SLOT_IRQ8		_BV(8)
#define SERIRQ_SLOT_IRQ7		_BV(7)
#define SERIRQ_SLOT_IRQ6		_BV(6)
#define SERIRQ_SLOT_IRQ5		_BV(5)
#define SERIRQ_SLOT_IRQ4		_BV(4)
#define SERIRQ_SLOT_IRQ3		_BV(3)
#define SERIRQ_SLOT_IRQ2		_BV(2)
#define SERIRQ_SLOT_IRQ1		_BV(1)
#define SERIRQ_SLOT_IRQ0		_BV(0)

/* 8.17 SERIRQ_SLOT_CLR */
#define SERIRQ_SLOT_IRQ31_CLR		_BV(31)
#define SERIRQ_SLOT_IRQ30_CLR		_BV(30)
#define SERIRQ_SLOT_IRQ29_CLR		_BV(29)
#define SERIRQ_SLOT_IRQ28_CLR		_BV(28)
#define SERIRQ_SLOT_IRQ27_CLR		_BV(27)
#define SERIRQ_SLOT_IRQ26_CLR		_BV(26)
#define SERIRQ_SLOT_IRQ25_CLR		_BV(25)
#define SERIRQ_SLOT_IRQ24_CLR		_BV(24)
#define SERIRQ_SLOT_IRQ23_CLR		_BV(23)
#define SERIRQ_SLOT_IRQ22_CLR		_BV(22)
#define SERIRQ_SLOT_IRQ21_CLR		_BV(21)
#define SERIRQ_SLOT_IRQ20_CLR		_BV(20)
#define SERIRQ_SLOT_IRQ19_CLR		_BV(19)
#define SERIRQ_SLOT_IRQ18_CLR		_BV(18)
#define SERIRQ_SLOT_IRQ17_CLR		_BV(17)
#define SERIRQ_SLOT_IRQ16_CLR		_BV(16)
#define SERIRQ_SLOT_IRQ15_CLR		_BV(15)
#define SERIRQ_SLOT_IRQ14_CLR		_BV(14)
#define SERIRQ_SLOT_IRQ13_CLR		_BV(13)
#define SERIRQ_SLOT_IRQ12_CLR		_BV(12)
#define SERIRQ_SLOT_IRQ11_CLR		_BV(11)
#define SERIRQ_SLOT_IRQ10_CLR		_BV(10)
#define SERIRQ_SLOT_IRQ9_CLR		_BV(9)
#define SERIRQ_SLOT_IRQ8_CLR		_BV(8)
#define SERIRQ_SLOT_IRQ7_CLR		_BV(7)
#define SERIRQ_SLOT_IRQ6_CLR		_BV(6)
#define SERIRQ_SLOT_IRQ5_CLR		_BV(5)
#define SERIRQ_SLOT_IRQ4_CLR		_BV(4)
#define SERIRQ_SLOT_IRQ3_CLR		_BV(3)
#define SERIRQ_SLOT_IRQ2_CLR		_BV(2)
#define SERIRQ_SLOT_IRQ1_CLR		_BV(1)
#define SERIRQ_SLOT_IRQ0_CLR		_BV(0)

/* 8.18 SERIRQ_DEBUG */
#define SERIRQ_DEBUG_SERIRQ_I		_BV(29)
#define SERIRQ_DEBUG_CURR_SERIRQ_MODE	_BV(28)
#define SERIRQ_DEBUG_STOP_COUNT		GENMASK(25, 24)
#define SERIRQ_DEBUG_STOP_IDLE_COUNT	GENMASK(21, 20)
#define SERIRQ_DEBUG_CYCLE3_COUNT	GENMASK(17, 16)
#define SERIRQ_DEBUG_SERIRQ_COUNT	GENMASK(12, 8)
#define SERIRQ_DEBUG_SERIRQ_FSM		GENMASK(6, 0)

/* 8.19 LPC_MEM_CFG */
#define LPC_MEM_CFG_TRANS		GENMASK(22, 16)
#define LPC_MEM_CFG_TRANS_SEL		_BV(8)
#define LPC_MEM_CFG_CYCLE		_BV(4)
#define LPC_MEM_CFG_RESERVED		_BV(0)

#endif /* __SPACEMIT_LPC_H_INCLUDE__ */