/*
 * ZETALOG's Personal COPYRIGHT
 *
 * Copyright (c) 2019
 *    ZETALOG - "Lv ZHENG".  All rights reserved.
 *    Author: Lv "Zetalog" Zheng
 *    Internet: zhenglv@hotmail.com
 *
 * This COPYRIGHT used to protect Personal Intelligence Rights.
 * Redistribution and use in source and binary forms with or without
 * modification, are permitted provided that the following conditions are
 * met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. All advertising materials mentioning features or use of this software
 *    must display the following acknowledgement:
 *    This product includes software developed by the Lv "Zetalog" ZHENG.
 * 3. Neither the name of this software nor the names of its developers may
 *    be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 * 4. Permission of redistribution and/or reuse of souce code partially only
 *    granted to the developer(s) in the companies ZETALOG worked.
 * 5. Any modification of this software should be published to ZETALOG unless
 *    the above copyright notice is no longer declaimed.
 *
 * THIS SOFTWARE IS PROVIDED BY THE ZETALOG AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE ZETALOG OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 *
 * @(#)spacemit_espi.h: SpacemiT eSPI interface
 * $Id: spacemit_espi.h,v 1.1 2023-11-27 16:50:00 zhenglv Exp $
 */

#ifndef __SPACEMIT_ESPI_H_INCLUDE__
#define __SPACEMIT_ESPI_H_INCLUDE__

#include <target/arch.h>
#include <asm/mach/espi.h>

#ifndef SPACEMIT_ESPI_REG
#define SPACEMIT_ESPI_REG(offset)		(SPACEMIT_ESPI_BASE + (offset))
#endif

/* Register offset */
#define ESPI_DN_TXHDR_0				SPACEMIT_ESPI_REG(0x00)
#define ESPI_DN_TXHDR_1				SPACEMIT_ESPI_REG(0x04)
#define ESPI_DN_TXHDR_2				SPACEMIT_ESPI_REG(0x08)
#define ESPI_DN_TXDATA_PORT			SPACEMIT_ESPI_REG(0x0C)
#define ESPI_UP_RXHDR_0				SPACEMIT_ESPI_REG(0x10)
#define ESPI_UP_RXHDR_1				SPACEMIT_ESPI_REG(0x14)
#define ESPI_UP_RXDATA_PORT			SPACEMIT_ESPI_REG(0x18)
#define ESPI_MASTER_CAP				SPACEMIT_ESPI_REG(0x2C)
#define ESPI_GLOBAL_CONTROL_0			SPACEMIT_ESPI_REG(0x30)
#define ESPI_GLOBAL_CONTROL_1			SPACEMIT_ESPI_REG(0x34)
#define ESPI_PR_BASE_ADDR_MEM0			SPACEMIT_ESPI_REG(0x38)
#define ESPI_PR_BASE_ADDR_MEM1			SPACEMIT_ESPI_REG(0x3C)
#define ESPI_SLAVE0_STS_SHADOW			SPACEMIT_ESPI_REG(0x44)
#define ESPI_SLAVE0_CONFIG			SPACEMIT_ESPI_REG(0x68)
#define ESPI_SLAVE0_INT_EN			SPACEMIT_ESPI_REG(0x6C)
#define ESPI_SLAVE0_INT_STS			SPACEMIT_ESPI_REG(0x70)
#define ESPI_SLAVE0_RXMSG_HDR0			SPACEMIT_ESPI_REG(0x74)
#define ESPI_SLAVE0_RXMSG_HDR1			SPACEMIT_ESPI_REG(0x78)
#define ESPI_SLAVE0_RXMSG_DATA_PORT		SPACEMIT_ESPI_REG(0x7C)
#define ESPI_SLAVE0_RXVW_STS			SPACEMIT_ESPI_REG(0x98)
#define ESPI_SLAVE0_RXVW			SPACEMIT_ESPI_REG(0x9C)
#define ESPI_SLAVE0_RXVW_DATA			SPACEMIT_ESPI_REG(0xA0)
#define ESPI_SLAVE0_RXVW_INDEX			SPACEMIT_ESPI_REG(0xA4)
#define ESPI_SLAVE0_VW_CTL			SPACEMIT_ESPI_REG(0xA8)
#define ESPI_SLAVE0_VW_POLARITY			SPACEMIT_ESPI_REG(0xAC)

/* DN_TXHDR_0 */
#define DN_TXHDR_0_DNCMD_HDATA2_MASK		GENMASK(31, 24)
#define DN_TXHDR_0_DNCMD_HDATA2(n)		FIELD_PREP(DN_TXHDR_0_DNCMD_HDATA2_MASK, n)
#define DN_TXHDR_0_DNCMD_HDATA1_MASK		GENMASK(23, 16)
#define DN_TXHDR_0_DNCMD_HDATA1(n)		FIELD_PREP(DN_TXHDR_0_DNCMD_HDATA1_MASK, n)
#define DN_TXHDR_0_DNCMD_HDATA0_MASK		GENMASK(15, 8)
#define DN_TXHDR_0_DNCMD_HDATA0(n)		FIELD_PREP(DN_TXHDR_0_DNCMD_HDATA2_MASK, n)
#define DN_TXHDR_0_DN_TXHDR_0_SLAVE_SEL_MASK	GENMASK(5, 4)
#define DN_TXHDR_0_DN_TXHDR_0_SLAVE_SEL(n)	FIELD_PREP(DN_TXHDR_0_DN_TXHDR_0_SLAVE_SEL_MASK, n)
#define DN_TXHDR_0_DNCMD_EN			_BV(3)
#define DN_TXHDR_0_DNCMD_TYPE_MASK		GENMASK(2, 0)
#define DN_TXHDR_0_DNCMD_TYPE(n)		FIELD_PREP(DN_TXHDR_0_DNCMD_TYPE_MASK, n)

/* DN_TXHDR_1 */
#define DN_TXHDR_1_DNCMD_HDATA6_MASK		GENMASK(31, 24)
#define DN_TXHDR_1_DNCMD_HDATA6(n)		FIELD_PREP(DN_TXHDR_1_DNCMD_HDATA6_MASK, n)
#define DN_TXHDR_1_DNCMD_HDATA5_MASK		GENMASK(23, 16)
#define DN_TXHDR_1_DNCMD_HDATA5(n)		FIELD_PREP(DN_TXHDR_1_DNCMD_HDATA5_MASK, n)
#define DN_TXHDR_1_DNCMD_HDATA4_MASK		GENMASK(15, 8)
#define DN_TXHDR_1_DNCMD_HDATA4(n)		FIELD_PREP(DN_TXHDR_1_DNCMD_HDATA4_MASK, n)
#define DN_TXHDR_1_DNCMD_HDATA3_MASK		GENMASK(7, 0)
#define DN_TXHDR_1_DNCMD_HDATA3(n)		FIELD_PREP(DN_TXHDR_1_DNCMD_HDATA3_MASK, n)

/* DN_TXHDR_2 */
#define DN_TXHDR_2_DNCMD_HDATA7_MASK		GENMASK(7, 0)
#define DN_TXHDR_2_DNCMD_HDATA7(n)		FIELD_PREP(DN_TXHDR_2_DNCMD_HDATA7_MASK, n)

/* UP_RXHDR_0 */
#define UP_RXHDR_0_UPCMD_HDATA2_MASK		GENMASK(31, 24)
#define UP_RXHDR_0_UPCMD_HDATA2(n)		FIELD_PREP(UP_RXHDR_0_UPCMD_HDATA2_MASK, n)
#define UP_RXHDR_0_UPCMD_HDATA1_MASK		GENMASK(23, 16)
#define UP_RXHDR_0_UPCMD_HDATA1(n)		FIELD_PREP(UP_RXHDR_0_UPCMD_HDATA1_MASK, n)
#define UP_RXHDR_0_UPCMD_HDATA0_MASK		GENMASK(15, 8)
#define UP_RXHDR_0_UPCMD_HDATA0(n)		FIELD_PREP(UP_RXHDR_0_UPCMD_HDATA0_MASK, n)
#define UP_RXHDR_0_UP_RXHDR_0_SLAVE_SEL_MASK	GENMASK(5, 4)
#define UP_RXHDR_0_UP_RXHDR_0_SLAVE_SEL(n)	FIELD_PREP(UP_RXHDR_0_UP_RXHDR_0_SLAVE_SEL_MASK, n)
#define UP_RXHDR_0_UPCMD_STATUS			_BV(3)
#define UP_RXHDR_0_UPCMD_TYPE_MASK		GENMASK(2, 0)
#define UP_RXHDR_0_UPCMD_TYPE			FIELD_PREP(UP_RXHDR_0_UPCMD_TYPE_MASK, n)

/* UP_RXHDR_1 */
#define UP_RXHDR_1_UPCMD_HDATA6_MASK		GENMASK(31, 24)
#define UP_RXHDR_1_UPCMD_HDATA6(n)		FIELD_PREP(UP_RXHDR_1_UPCMD_HDATA6_MASK, n)
#define UP_RXHDR_1_UPCMD_HDATA5_MASK		GENMASK(23, 16)
#define UP_RXHDR_1_UPCMD_HDATA5(n)		FIELD_PREP(UP_RXHDR_1_UPCMD_HDATA5_MASK, n)
#define UP_RXHDR_1_UPCMD_HDATA4_MASK		GENMASK(15, 8)
#define UP_RXHDR_1_UPCMD_HDATA4(n)		FIELD_PREP(UP_RXHDR_1_UPCMD_HDATA4_MASK, n)
#define UP_RXHDR_1_UPCMD_HDATA3_MASK		GENMASK(7, 0)
#define UP_RXHDR_1_UPCMD_HDATA3(n)		FIELD_PREP(UP_RXHDR_1_UPCMD_HDATA3_MASK, n)

/* MASTER_CAP */
#define MASTER_CAP_CRC_CHECK_SUPPORT		_BV(31)
#define MASTER_CAP_ALERT_MODE_SUPPORT		_BV(30)
#define MASTER_CAP_IO_MODE_SUPPORT_MASK		GENMASK(29, 28)
#define MASTER_CAP_IO_MODE_SUPPORT(n)		FIELD_PREP(MASTER_CAP_IO_MODE_SUPPORT_MASK, n)
#define MASTER_CAP_CLK_FREQ_SUPPORT_MASK	GENMASK(27, 25)
#define MASTER_CAP_CLK_FREQ_SUPPORT(n)		FIELD_PREP(MASTER_CAP_CLK_FREQ_SUPPORT_MASK, n)
#define MASTER_CAP_SLAVE_NUM_MASK		GENMASK(24, 22)
#define MASTER_CAP_SLAVE_NUM(n)			FIELD_PREP(MASTER_CAP_SLAVE_NUM_MASK, n)
#define MASTER_CAP_PR_MAX_SIZE_MASK		GENMASK(21, 19)
#define MASTER_CAP_PR_MAX_SIZE(n)		FIELD_PREP(MASTER_CAP_PR_MAX_SIZE_MASK, n)
#define MASTER_CAP_VW_MAX_SIZE_MASK		GENMASK(18, 13)
#define MASTER_CAP_VW_MAX_SIZE(n)		FIELD_PREP(MASTER_CAP_VW_MAX_SIZE_MASK, n)
#define MASTER_CAP_OOB_MAX_SIZE_MASK		GENMASK(12, 10)
#define MASTER_CAP_OOB_MAX_SIZE(n)		FIELD_PREP(MASTER_CAP_OOB_MAX_SIZE_MASK, n)
#define MASTER_CAP_FLASH_MAX_SIZE_MASK		GENMASK(9, 7)
#define MASTER_CAP_FLASH_MAX_SIZE(n)		FIELD_PREP(MASTER_CAP_FLASH_MAX_SIZE_MASK, n)
#define MASTER_CAP_ESPI_VERSION_MASK		GENMASK(6, 4)
#define MASTER_CAP_ESPI_VERSION(n)		FIELD_PREP(MASTER_CAP_ESPI_VERSION_MASK, n)
#define MASTER_CAP_PR_SUPPORT			_BV(3)
#define MASTER_CAP_VW_SUPPORT			_BV(2)
#define MASTER_CAP_OOB_SUPPORT			_BV(1)
#define MASTER_CAP_FLASH_SUPPORT		_BV(0)

/* GLOBAL_CONTROL_0 */
#define GLOBAL_CONTROL_0_WAIT_CNT_MASK		GENMASK(29, 24)
#define GLOBAL_CONTROL_0_WAIT_CNT(n)		FIELD_PREP(GLOBAL_CONTROL_0_WAIT_CNT_MASK, n)
#define GLOBAL_CONTROL_0_WDG_CNT_MASK		GENMASK(23, 8)
#define GLOBAL_CONTROL_0_WDG_CNT(n)		FIELD_PREP(GLOBAL_CONTROL_0_WDG_CNT_MASK, n)
#define GLOBAL_CONTROL_0_MST_IDLE_CNT_MASK	GENMASK(6, 4)
#define GLOBAL_CONTROL_0_MST_IDLE_CNT(n)	FIELD_PREP(GLOBAL_CONTROL_0_MST_IDLE_CNT_MASK, n)
#define GLOBAL_CONTROL_0_MST_STOP_EN		_BV(3)
#define GLOBAL_CONTROL_0_WAIT_CHK_EN_MASK	_BV(1)
#define GLOBAL_CONTROL_0_WDG_EN_MASK		_BV(0)

/* GLOBAL_CONTROL_1 */
#define GLOBAL_CONTROL_1_NP_FORCE_EN		_BV(7)
#define GLOBAL_CONTROL_1_SUS_STAT		_BV(6)
#define GLOBAL_CONTROL_1_SW_RST			_BV(0)

/* PR_CONFIG */
#define PR_CONFIG_PR_SWITCH			_BV(31)
#define PR_CONFIG_PR_BUSY			_BV(30)
#define PR_CONFIG_PR_WR_BUSY			_BV(29)
#define PR_CONFIG_PR_RD_BUSY			_BV(28)
#define PR_CONFIG_RX_OVERFLOW			_BV(25)
#define PR_CONFIG_RX_DATA_NUM_MASK		GENMASK(24, 21)
#define PR_CONFIG_RX_DATA_NUM(n)		FIELD_PREP(PR_CONFIG_RX_DATA_NUM_MASK, n)
#define PR_CONFIG_TX_OVERFLOW			_BV(20)
#define PR_CONFIG_TX_DATA_NUM_MASK		GENMASK(19, 16)
#define PR_CONFIG_TX_DATA_NUM(n)		FIELD_PREP(PR_CONFIG_TX_DATA_NUM_MASK, n)
#define PR_CONFIG_PR_CNT_MASK			GENMASK(14, 8)
#define PR_CONFIG_PR_CNT(n)			FIELD_PREP(PR_CONFIG_PR_CNT_MASK, n)
#define PR_CONFIG_PR_IO_MEM_SEL			_BV(2)
#define PR_CONFIG_PR_WR_RD			_BV(1)
#define PR_CONFIG_PR_TRANS_EN			_BV(0)

/* SLAVE0_STS_SHADOW */
#define SLAVE0_STS_SHADOW_STS_SHADOW_MASK	GENMASK(31, 16)
#define SLAVE0_STS_SHADOW_STS_SHADOW(n)		FIELD_PREP(SLAVE0_STS_SHADOW_STS_SHADOW_MASK, n)
#define SLAVE0_STS_SHADOW_STS_SHADOW_EN		_BV(0)

/* SLAVE0_CONFIG */
#define SLAVE0_CONFIG_CRC_CHECK_EN		_BV(31)
#define SLAVE0_CONFIG_ALERT_MODE_SEL		_BV(30)
#define SLAVE0_CONFIG_IO_MODE_SEL_MASK		GENMASK(29, 28)
#define SLAVE0_CONFIG_IO_MODE_SEL(n)		FIELD_PREP(SLAVE0_CONFIG_IO_MODE_SEL_MASK, n)
#define SLAVE0_CONFIG_CLK_FREQ_SEL_MASK		GENMASK(27, 25)
#define SLAVE0_CONFIG_CLK_FREQ_SEL(n)		FIELD_PREP(SLAVE0_CONFIG_CLK_FREQ_SEL_MASK, n)
#define SLAVE0_CONFIG_PR_EN			_BV(3)
#define SLAVE0_CONFIG_VW_EN			_BV(2)
#define SLAVE0_CONFIG_OOB_EN			_BV(1)
#define SLAVE0_CONFIG_FLASH_EN			_BV(0)

/* SLAVE0_INT_EN */
#define SLAVE0_CONFIG_FLASH_REQ_INT_EN		_BV(31)
#define SLAVE0_INT_EN_RXOOB_INT_EN		_BV(30)
#define SLAVE0_INT_EN_RXMSG_INT_EN		_BV(29)
#define SLAVE0_INT_EN_DNCMD_INT_EN		_BV(28)
#define SLAVE0_INT_EN_RXVW_GPR3_INT_EN		_BV(27)
#define SLAVE0_INT_EN_RXVW_GPR2_INT_EN		_BV(26)
#define SLAVE0_INT_EN_RXVW_GPR1_INT_EN		_BV(25)
#define SLAVE0_INT_EN_RXVW_GPR0_INT_EN		_BV(24)
#define SLAVE0_INT_EN_PR_INT_EN			_BV(23)
#define SLAVE0_INT_EN_PROTOCOL_ERR_INT_EN	_BV(15)
#define SLAVE0_INT_EN_RXFLASH_OFLOW_INT_EN	_BV(14)
#define SLAVE0_INT_EN_RXMSG_OFLOW_INT_EN	_BV(13)
#define SLAVE0_INT_EN_RXOOB_OFLOW_INT_EN	_BV(12)
#define SLAVE0_INT_EN_ILLEGAL_LEN_INT_EN	_BV(11)
#define SLAVE0_INT_EN_ILLEGAL_TAG_INT_EN	_BV(10)
#define SLAVE0_INT_EN_UNSUCSS_CPL_INT_EN	_BV(9)
#define SLAVE0_INT_EN_INVALID_CT_RSP_INT_EN	_BV(8)
#define SLAVE0_INT_EN_INVALID_ID_RSP_INT_EN	_BV(7)
#define SLAVE0_INT_EN_NON_FATAL_INT_EN		_BV(6)
#define SLAVE0_INT_EN_FATAL_ERR_INT_EN		_BV(5)
#define SLAVE0_INT_EN_NO_RSP_INT_EN		_BV(4)
#define SLAVE0_INT_EN_CRC_ERR_INT_EN		_BV(2)
#define SLAVE0_INT_EN_WAIT_TIMEOUT_INT_EN	_BV(1)
#define SLAVE0_INT_EN_BUS_ERR_INT_EN		_BV(0)

/* SLAVE0_INT_STS */
#define SLAVE0_INT_STS_FLASH_REQ_INT		_BV(31)
#define SLAVE0_INT_STS_RXOOB_INT		_BV(30)
#define SLAVE0_INT_STS_RXMSG_INT		_BV(29)
#define SLAVE0_INT_STS_DNCMD_INT		_BV(28)
#define SLAVE0_INT_STS_RXVW_GRP3_INT		_BV(27)
#define SLAVE0_INT_STS_RXVW_GRP2_INT		_BV(26)
#define SLAVE0_INT_STS_RXVW_GRP1_INT		_BV(25)
#define SLAVE0_INT_STS_RXVW_GRP0_INT		_BV(24)
#define SLAVE0_INT_STS_PR_INT			_BV(23)
#define SLAVE0_INT_STS_WDT_TIMEOUT_INT		_BV(19)
#define SLAVE0_INT_STS_MST_ABORT_INT		_BV(18)
#define SLAVE0_INT_STS_PROTOCOL_ERR_INT		_BV(15)
#define SLAVE0_INT_STS_RXFLASH_OFLOW_INT	_BV(14)
#define SLAVE0_INT_STS_RXMSG_OFLOW_INT		_BV(13)
#define SLAVE0_INT_STS_RXOOB_OFLOW_INT		_BV(12)
#define SLAVE0_INT_STS_ILLEGAL_LEN_INT		_BV(11)
#define SLAVE0_INT_STS_ILLEGAL_TAG_INT		_BV(10)
#define SLAVE0_INT_STS_UNSUCSS_CPL_INT		_BV(9)
#define SLAVE0_INT_STS_INVALID_CT_RSP_INT	_BV(8)
#define SLAVE0_INT_STS_INVALID_ID_RSP_INT	_BV(7)
#define SLAVE0_INT_STS_NON_FATAL_INT		_BV(6)
#define SLAVE0_INT_STS_FATAL_ERR_INT		_BV(5)
#define SLAVE0_INT_STS_NO_RSP_INT		_BV(4)
#define SLAVE0_INT_STS_CRC_ERR_INT		_BV(2)
#define SLAVE0_INT_STS_WAIT_TIMEOUT_INT		_BV(1)
#define SLAVE0_INT_STS_BUS_ERRINT		_BV(0)

/* SLAVE0_RXMSG_HDR0 */
#define SLAVE0_RXMSG_HDR0_RXMSG_HDATA2_MASK	GENMASK(31, 24)
#define SLAVE0_RXMSG_HDR0_RXMSG_HDATA2(n)	FIELD_PREP(SLAVE0_RXMSG_HDR0_RXMSG_HDATA2_MASK, n)
#define SLAVE0_RXMSG_HDR0_RXMSG_HDATA1_MASK	GENMASK(23, 16)
#define SLAVE0_RXMSG_HDR0_RXMSG_HDATA1(n)	FIELD_PREP(SLAVE0_RXMSG_HDR0_RXMSG_HDATA1_MASK, n)
#define SLAVE0_RXMSG_HDR0_RXMSG_HDATA0_MASK	GENMASK(15, 8)
#define SLAVE0_RXMSG_HDR0_RXMSG_HDATA0(n)	FIELD_PREP(SLAVE0_RXMSG_HDR0_RXMSG_HDATA0_MASK, n)
#define SLAVE0_RXMSG_HDR0_RXMSG_TYPE_MASK	GENMASK(7, 0)
#define SLAVE0_RXMSG_HDR0_RXMSG_TYPE(n)	FIELD_PREP(SLAVE0_RXMSG_HDR0_RXMSG_TYPE_MASK, n)

/* SLAVE0_RXMSG_HDR1 */
#define SLAVE0_RXMSG_HDR1_SPECIFIC_HDATA3_MASK	GENMASK(31, 24)
#define SLAVE0_RXMSG_HDR1_SPECIFIC_HDATA3(n)	FIELD_PREP(SLAVE0_RXMSG_HDR1_SPECIFIC_HDATA3_MASK, n)
#define SLAVE0_RXMSG_HDR1_SPECIFIC_HDATA2_MASK	GENMASK(23, 16)
#define SLAVE0_RXMSG_HDR1_SPECIFIC_HDATA2(n)	FIELD_PREP(SLAVE0_RXMSG_HDR1_SPECIFIC_HDATA2_MASK, n)
#define SLAVE0_RXMSG_HDR1_SPECIFIC_HDATA1_MASK	GENMASK(15, 8)
#define SLAVE0_RXMSG_HDR1_SPECIFIC_HDATA1(n)	FIELD_PREP(SLAVE0_RXMSG_HDR1_SPECIFIC_HDATA1_MASK, n)
#define SLAVE0_RXMSG_HDR1_SPECIFIC_HDATA0_MASK	GENMASK(7, 0)
#define SLAVE0_RXMSG_HDR1_SPECIFIC_HDATA0(n)	FIELD_PREP(SLAVE0_RXMSG_HDR1_SPECIFIC_HDATA0_MASK, n)

/* SLAVE0_RXVW_STS */
#define SLAVE0_RXVW_STS_SYS_EVT_STS		_BV(29)
#define SLAVE0_RXVW_STS_IRQ23_STS		_BV(23)
#define SLAVE0_RXVW_STS_IRQ22_STS		_BV(22)
#define SLAVE0_RXVW_STS_IRQ21_STS		_BV(21)
#define SLAVE0_RXVW_STS_IRQ20_STS		_BV(20)
#define SLAVE0_RXVW_STS_IRQ19_STS		_BV(19)
#define SLAVE0_RXVW_STS_IRQ18_STS		_BV(18)
#define SLAVE0_RXVW_STS_IRQ17_STS		_BV(17)
#define SLAVE0_RXVW_STS_IRQ16_STS		_BV(16)
#define SLAVE0_RXVW_STS_IRQ15_STS		_BV(15)
#define SLAVE0_RXVW_STS_IRQ14_STS		_BV(14)
#define SLAVE0_RXVW_STS_IRQ13_STS		_BV(13)
#define SLAVE0_RXVW_STS_IRQ12_STS		_BV(12)
#define SLAVE0_RXVW_STS_IRQ11_STS		_BV(11)
#define SLAVE0_RXVW_STS_IRQ10_STS		_BV(10)
#define SLAVE0_RXVW_STS_IRQ9_STS		_BV(9)
#define SLAVE0_RXVW_STS_IRQ8_STS		_BV(8)
#define SLAVE0_RXVW_STS_IRQ7_STS		_BV(7)
#define SLAVE0_RXVW_STS_IRQ6_STS		_BV(6)
#define SLAVE0_RXVW_STS_IRQ5_STS		_BV(5)
#define SLAVE0_RXVW_STS_IRQ4_STS		_BV(4)
#define SLAVE0_RXVW_STS_IRQ3_STS		_BV(3)
#define SLAVE0_RXVW_STS_IRQ2_STS		_BV(2)
#define SLAVE0_RXVW_STS_IRQ1_STS		_BV(1)
#define SLAVE0_RXVW_STS_IRQ0_STS		_BV(0)

/* SLAVE0_RXVW */
#define SLAVE0_RXVW_HOST_RST_ACK		_BV(19)
#define SLAVE0_RXVW_RCIN			_BV(18)
#define SLAVE0_RXVW_SMI				_BV(17)
#define SLAVE0_RXVW_SCI				_BV(16)
#define SLAVE0_RXVW_SLAVE0_BOOT_LOAD_STS	_BV(15)
#define SLAVE0_RXVW_SLAVE0_ERROR_NONFATAL	_BV(14)
#define SLAVE0_RXVW_SLAVE0_ERROR_FATAL		_BV(13)
#define SLAVE0_RXVW_SLAVE0_BOOT_LOAD_DONE	_BV(12)
#define SLAVE0_RXVW_PME				_BV(11)
#define SLAVE0_RXVW_WAKE			_BV(10)
#define SLAVE0_RXVW_OOB_RST_ACK			_BV(8)
#define SLAVE0_RXVW_DNX_ACK			_BV(1)
#define SLAVE0_RXVW_SUS_ACK_B			_BV(0)

/* SLAVE0_RXVW_DATA */
#define SLAVE0_RXVW_DATA_GRP3_MASK		GENMASK(31, 24)
#define SLAVE0_RXVW_DATA_GRP3(n)		FIELD_PREP(SLAVE0_RXVW_DATA_GRP3_MASK, n)
#define SLAVE0_RXVW_DATA_GRP2_MASK		GENMASK(23, 16)
#define SLAVE0_RXVW_DATA_GRP2(n)		FIELD_PREP(SLAVE0_RXVW_DATA_GRP2_MASK, n)
#define SLAVE0_RXVW_DATA_GRP1_MASK		GENMASK(15, 8)
#define SLAVE0_RXVW_DATA_GRP1(n)		FIELD_PREP(SLAVE0_RXVW_DATA_GRP1_MASK, n)
#define SLAVE0_RXVW_DATA_GRP0_MASK		GENMASK(7, 0)
#define SLAVE0_RXVW_DATA_GRP0(n)		FIELD_PREP(SLAVE0_RXVW_DATA_GRP0_MASK, n)

/* SLAVE0_RXVW_INDEX */
#define SLAVE0_RXVW_INDEX_GRP3_MASK		GENMASK(31, 24)
#define SLAVE0_RXVW_INDEX_GRP3(n)		FIELD_PREP(SLAVE0_RXVW_INDEX_GRP3_MASK, n)
#define SLAVE0_RXVW_INDEX_GRP2_MASK		GENMASK(23, 16)
#define SLAVE0_RXVW_INDEX_GRP2(n)		FIELD_PREP(SLAVE0_RXVW_INDEX_GRP2_MASK, n)
#define SLAVE0_RXVW_INDEX_GRP1_MASK		GENMASK(15, 8)
#define SLAVE0_RXVW_INDEX_GRP1(n)		FIELD_PREP(SLAVE0_RXVW_INDEX_GRP1_MASK, n)
#define SLAVE0_RXVW_INDEX_GRP0_MASK		GENMASK(7, 0)
#define SLAVE0_RXVW_INDEX_GRP0(n)		FIELD_PREP(SLAVE0_RXVW_INDEX_GRP0_MASK, n)

/* SLAVE0_VW_CTL */
#define SLAVE0_VW_CTL_IRQ23_MASK		_BV(23)
#define SLAVE0_VW_CTL_IRQ22_MASK		_BV(22)
#define SLAVE0_VW_CTL_IRQ21_MASK		_BV(21)
#define SLAVE0_VW_CTL_IRQ20_MASK		_BV(20)
#define SLAVE0_VW_CTL_IRQ19_MASK		_BV(19)
#define SLAVE0_VW_CTL_IRQ18_MASK		_BV(18)
#define SLAVE0_VW_CTL_IRQ17_MASK		_BV(17)
#define SLAVE0_VW_CTL_IRQ16_MASK		_BV(16)
#define SLAVE0_VW_CTL_IRQ15_MASK		_BV(15)
#define SLAVE0_VW_CTL_IRQ14_MASK		_BV(14)
#define SLAVE0_VW_CTL_IRQ13_MASK		_BV(13)
#define SLAVE0_VW_CTL_IRQ12_MASK		_BV(12)
#define SLAVE0_VW_CTL_IRQ11_MASK		_BV(11)
#define SLAVE0_VW_CTL_IRQ10_MASK		_BV(10)
#define SLAVE0_VW_CTL_IRQ9_MASK			_BV(9)
#define SLAVE0_VW_CTL_IRQ8_MASK			_BV(8)
#define SLAVE0_VW_CTL_IRQ7_MASK			_BV(7)
#define SLAVE0_VW_CTL_IRQ6_MASK			_BV(6)
#define SLAVE0_VW_CTL_IRQ5_MASK			_BV(5)
#define SLAVE0_VW_CTL_IRQ4_MASK			_BV(4)
#define SLAVE0_VW_CTL_IRQ3_MASK			_BV(3)
#define SLAVE0_VW_CTL_IRQ2_MASK			_BV(2)
#define SLAVE0_VW_CTL_IRQ1_MASK			_BV(1)
#define SLAVE0_VW_CTL_IRQ0_MASK			_BV(0)

/* SLAVE0_VW_POLARITY */
#define SLAVE0_VW_POLARITY_IRQ23_POLARITY	_BV(23)
#define SLAVE0_VW_POLARITY_IRQ22_POLARITY	_BV(22)
#define SLAVE0_VW_POLARITY_IRQ21_POLARITY	_BV(21)
#define SLAVE0_VW_POLARITY_IRQ20_POLARITY	_BV(20)
#define SLAVE0_VW_POLARITY_IRQ19_POLARITY	_BV(19)
#define SLAVE0_VW_POLARITY_IRQ18_POLARITY	_BV(18)
#define SLAVE0_VW_POLARITY_IRQ17_POLARITY	_BV(17)
#define SLAVE0_VW_POLARITY_IRQ16_POLARITY	_BV(16)
#define SLAVE0_VW_POLARITY_IRQ15_POLARITY	_BV(15)
#define SLAVE0_VW_POLARITY_IRQ14_POLARITY	_BV(14)
#define SLAVE0_VW_POLARITY_IRQ13_POLARITY	_BV(13)
#define SLAVE0_VW_POLARITY_IRQ12_POLARITY	_BV(12)
#define SLAVE0_VW_POLARITY_IRQ11_POLARITY	_BV(11)
#define SLAVE0_VW_POLARITY_IRQ10_POLARITY	_BV(10)
#define SLAVE0_VW_POLARITY_IRQ9_POLARITY	_BV(9)
#define SLAVE0_VW_POLARITY_IRQ8_POLARITY	_BV(8)
#define SLAVE0_VW_POLARITY_IRQ7_POLARITY	_BV(7)
#define SLAVE0_VW_POLARITY_IRQ6_POLARITY	_BV(6)
#define SLAVE0_VW_POLARITY_IRQ5_POLARITY	_BV(5)
#define SLAVE0_VW_POLARITY_IRQ4_POLARITY	_BV(4)
#define SLAVE0_VW_POLARITY_IRQ3_POLARITY	_BV(3)
#define SLAVE0_VW_POLARITY_IRQ2_POLARITY	_BV(2)
#define SLAVE0_VW_POLARITY_IRQ1_POLARITY	_BV(1)
#define SLAVE0_VW_POLARITY_IRQ0_POLARITY	_BV(0)

#define ESPI_DECODE_RANGES_PER_REG_GROUP	4

#endif /* __SPACEMIT_EPSI_H_INCLUDE__ */
