#ifndef __IOPMP_RISCV_H_INCLUDE__
#define __IOPMP_RISCV_H_INCLUDE__

#define IOPMP_INFO(n)		IOPMP_REG(0x0000 + (n))
#define IOPMP_MDCFG(n)		IOPMP_REG(0x0800 + ((n) << 2))
#define IOPMP_SRCMD(n, s)	IOPMP_REG(0x1000 + (n) + ((s) << 5))
#define IOPMP_ENTRY(n, i)	IOPMP_REG(__raw_readl(IOPMP_ENTRYOFFSET) + (n) + ((i) << 4))

#define IOPMP_VERSION		IOPMP_INFO(0x0000)
#define IOPMP_IMPLEMENTATION	IOPMP_INFO(0x0004)
#define IOPMP_HWCFG0		IOPMP_INFO(0x0008)
#define IOPMP_HWCFG1		IOPMP_INFO(0x000C)
#define IOPMP_HWCFG2		IOPMP_INFO(0x0010)
#define IOPMP_ENTRYOFFSET	IOPMP_INFO(0x0014)
#define IOPMP_MDSTALL		IOPMP_INFO(0x0030)
#define IOPMP_MDSTALLH		IOPMP_INFO(0x0034)
#define IOPMP_RRIDSCP		IOPMP_INFO(0x0038)
#define IOPMP_MDLCK		IOPMP_INFO(0x0040)
#define IOPMP_MDLCKH		IOPMP_INFO(0x0044)
#define IOPMP_MDCFGLCK		IOPMP_INFO(0x0048)
#define IOPMP_ENTRYLCK		IOPMP_INFO(0x004C)
#define IOPMP_ERR_CFG		IOPMP_INFO(0x0060)
#define IOPMP_ERR_REQINFO	IOPMP_INFO(0x0064)
#define IOPMP_ERR_REQADDR	IOPMP_INFO(0x0068)
#define IOPMP_ERR_REQADDRH	IOPMP_INFO(0x006C)
#define IOPMP_ERR_REQID		IOPMP_INFO(0x0070)
#define IOPMP_ERR_MFR		IOPMP_INFO(0x0074)
#define IOPMP_ERR_USER(n)	IOPMP_INFO(0x0080 + ((n) << 2))

#define IOPMP_SRCMD_EN(s)	IOPMP_SRCMD(0x0000, s)
#define IOPMP_SRCMD_ENH(s)	IOPMP_SRCMD(0x0004, s)
#define IOPMP_SRCMD_R(s)	IOPMP_SRCMD(0x0008, s)
#define IOPMP_SRCMD_RH(s)	IOPMP_SRCMD(0x000C, s)
#define IOPMP_SRCMD_W(s)	IOPMP_SRCMD(0x0010, s)
#define IOPMP_SRCMD_WH(s)	IOPMP_SRCMD(0x0014, s)

#define IOPMP_ENTRY_ADDR(i)	IOPMP_ENTRY(0x0000, i)
#define IOPMP_ENTRY_ADDRH(i)	IOPMP_ENTRY(0x0004, i)
#define IOPMP_ENTRY_CFG(i)	IOPMP_ENTRY(0x0008, i)
#define IOPMP_ENTRY_USER_CFG(i)	IOPMP_ENTRY(0x000C, i)

#endif /* __IOPMP_RISCV_H_INCLUDE__ */
