#ifndef __X60_HPM_H_INCLUDE__
#define __X60_HPM_H_INCLUDE__

#define HPM_EVENT_BRANCHES		1
#define HPM_EVENT_BRANCH_MISPREDS	2
#define HPM_EVENT_L1DC_READ_MISS	5
#define HPM_EVENT_L1DC_READS		6
#define HPM_EVENT_L1DC_WRITE_MISS	9
#define HPM_EVENT_L1DC_WRITES		10
#define HPM_EVENT_L1IC_READ_MISS	11
#define HPM_EVENT_L1IC_READS		12
#define HPM_EVENT_DTLB_LOAD_MISS	21
#define HPM_EVENT_DTLB_STORE_MISS	25
#define HPM_EVENT_ITLB_EXEC_MISS	27
#define HPM_EVENT_L1DC_ACCESSES		170
#define HPM_EVENT_L1DC_MISS		171
#define HPM_EVENT_L2DC_READS		184
#define HPM_EVENT_L2DC_READ_MISS	185
#define HPM_EVENT_L2DC_WRITES		188

#endif /* __X60_HPM_H_INCLUDE__ */
