# Copyright (C) 2008 by Lv Zheng <lv.zheng@soliton.com.cn>
#
# Licensed under the GPL v2, see the file LICENSE in this tarball.

obj-y:=

obj-y += uart_core.rel
obj-$(CONFIG_UART_SYNC) += uart_sync.rel
obj-$(CONFIG_UART_ASYNC) += uart_async.rel

