obj-y :=

CFLAGS += -I$(srctree)/include/tests/riscv/iommu

# obj-y += iommu_atc.o
# obj-y += iommu_ats.o
# obj-y += iommu_command_queue.o
# obj-y += iommu_device_context.o
# obj-y += iommu_faults.o
# obj-y += iommu_hpm.o
# obj-y += iommu_interrupt.o
# obj-y += iommu_msi_trans.o
# obj-y += iommu_process_context.o
# obj-y += iommu_reg.o
# obj-y += iommu_second_stage_trans.o
# obj-y += iommu_translate.o
# obj-y += iommu_two_stage_trans.o
# obj-y += iommu_utils.o
