
obj-y :=

obj-y += board.rel
obj-y += cpu.rel
obj-y += clk.rel
obj-y += pm.rel
obj-y += irq.rel
obj-y += vic.rel
obj-y += tsc.rel

obj-$(CONFIG_GPT_LM3S3826) += gpt.rel
obj-$(CONFIG_GPIO_LM3S3826) += gpio.rel
obj-$(CONFIG_KBD_LM3S3826) += kbd.rel
obj-$(CONFIG_UART_LM3S3826) += uart.rel
obj-$(CONFIG_SSI_LM3S3826) += ssi.rel
