
obj-y :=

obj-y += board.rel
obj-y += cpu.rel
obj-y += clk.rel
obj-y += pm.rel
obj-y += irq.rel
obj-y += vic.rel
obj-y += tsc.rel

obj-$(CONFIG_GPT_LM3S9B92) += gpt.rel
obj-$(CONFIG_GPIO_LM3S9B92) += gpio.rel
obj-$(CONFIG_UART_LM3S9B92) += uart.rel
obj-$(CONFIG_LED_LM3S9B92) += led.rel
obj-$(CONFIG_SSI_LM3S9B92) += ssi.rel
obj-$(CONFIG_FLASH_LM3S9B92) += flash.rel

obj-$(CONFIG_USB_LM3S9B92) += usb.rel
obj-$(CONFIG_USB_LM3S9B92_DEV) += usb_dev.rel
obj-$(CONFIG_USB_LM3S9B92_HCD) += usb_hcd.rel

obj-$(CONFIG_IFDS_LM3S9B92) += ifds.rel
