#ifndef __REG_GEM5_H_INCLUDE__
#define __REG_GEM5_H_INCLUDE__

#define RAM_START		0x0000000000
#define RAM_SIZE		0x0004000000
#define RAM_END			(RAM_START + RAM_SIZE)

#define ROM_BASE		RAM_START
#define ROMEND			RAM_END

#define RAM_BASE		RAM_START
#define RAMEND			RAM_END

#endif /* __REG_GEM5_H_INCLUDE__ */
