
/*
 * ZETALOG's Personal COPYRIGHT
 *
 * Copyright (c) 2024
 *    ZETALOG - "Lv ZHENG".  All rights reserved.
 *    Author: Lv "Zetalog" Zheng
 *    Internet: zhenglv@hotmail.com
 *
 * This COPYRIGHT used to protect Personal Intelligence Rights.
 * Redistribution and use in source and binary forms with or without
 * modification, are permitted provided that the following conditions are
 * met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. All advertising materials mentioning features or use of this software
 *    must display the following acknowledgement:
 *    This product includes software developed by the Lv "Zetalog" ZHENG.
 * 3. Neither the name of this software nor the names of its developers may
 *    be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 * 4. Permission of redistribution and/or reuse of souce code partially only
 *    granted to the developer(s) in the companies ZETALOG worked.
 * 5. Any modification of this software should be published to ZETALOG unless
 *    the above copyright notice is no longer declaimed.
 *
 * THIS SOFTWARE IS PROVIDED BY THE ZETALOG AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE ZETALOG OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 *
 * @(#)crg.h: k1matrix clock/reset generator definitions
 * $Id: crg.h,v 1.1 2024-06-05 17:37:00 zhenglv Exp $
 */

#ifndef __K1MATRIX_CRG_H_INCLUDE__
#define __K1MATRIX_CRG_H_INCLUDE__

#define CRG_BASE			__RMU_SYS_CRG_BASE
#define SC_PLLTS12FFC_BASE(n)		CRG_REG(0x00C * (n))

#include <driver/sc_pllts12ffclafrac2.h>

#define CRG_REG(offset)			(CRG_BASE + (offset))

#define CRG_COMPLL_CTL			CRG_REG(0x000)
#define CRG_COMPLL_CFG1			CRG_REG(0x004)
#define CRG_COMPLL_CFG2			CRG_REG(0x008)
#define CRG_MESH_PLL_CTL		CRG_REG(0x00C)
#define CRG_MESH_PLL_CFG1		CRG_REG(0x010)
#define CRG_MESH_PLL_CFG2		CRG_REG(0x014)
#define CRG_PERI_PLL_CTL		CRG_REG(0x018)
#define CRG_PERI_PLL_CFG1		CRG_REG(0x01C)
#define CRG_PERI_PLL_CFG2		CRG_REG(0x020)
#define CRG_DDR0_PLL_CTL		CRG_REG(0x024)
#define CRG_DDR0_PLL_CFG1		CRG_REG(0x028)
#define CRG_DDR0_PLL_CFG2		CRG_REG(0x02C)
#define CRG_DDR1_PLL_CTL		CRG_REG(0x030)
#define CRG_DDR1_PLL_CFG1		CRG_REG(0x034)
#define CRG_DDR1_PLL_CFG2		CRG_REG(0x038)
#define CRG_CPU0_PLL_CTL		CRG_REG(0x03C)
#define CRG_CPU0_PLL_CFG1		CRG_REG(0x040)
#define CRG_CPU0_PLL_CFG2		CRG_REG(0x044)
#define CRG_CPU1_PLL_CTL		CRG_REG(0x048)
#define CRG_CPU1_PLL_CFG1		CRG_REG(0x04C)
#define CRG_CPU1_PLL_CFG2		CRG_REG(0x050)
#define CRG_CPU_CLK_CTL			CRG_REG(0x100)
#define CRG_CPU_NIC_CLK_CTL		CRG_REG(0x104)
#define CRG_CPU_HAP_CLK_CTL		CRG_REG(0x108)
#define CRG_PCIE_TOP_CLK_CTL		CRG_REG(0x110)
#define CRG_PCIE_TOP_AUXCLK_CTL		CRG_REG(0x114)
#define CRG_PCIE_TOP_CFGCLK_CTL		CRG_REG(0x118)
#define CRG_PCIE_BOT_CLK_CTL		CRG_REG(0x120)
#define CRG_PCIE_BOT_AUXCLK_CTL		CRG_REG(0x124)
#define CRG_PCIE_BOT_CFGCLK_CTL		CRG_REG(0x128)
#define CRG_PERI_SUB_CLK_CTL		CRG_REG(0x130)
#define CRG_MESH_SUB_CLK_CTL		CRG_REG(0x140)
#define CRG_DDR_SUB_CLK_CTL		CRG_REG(0x150)
#define CRG_CLUSTER0_CLK_CTL		CRG_REG(0x200)
#define CRG_CLUSTER1_CLK_CTL		CRG_REG(0x204)
#define CRG_CLUSTER2_CLK_CTL		CRG_REG(0x208)
#define CRG_CLUSTER3_CLK_CTL		CRG_REG(0x20C)
#define CRG_CLUSTER4_CLK_CTL		CRG_REG(0x210)
#define CRG_CLUSTER5_CLK_CTL		CRG_REG(0x214)
#define CRG_CLUSTER6_CLK_CTL		CRG_REG(0x218)
#define CRG_CLUSTER7_CLK_CTL		CRG_REG(0x21C)
#define CRG_SYS_APB_CLK_CTL		CRG_REG(0x220)
#define CRG_APIC_CLK_CTL		CRG_REG(0x224)
#define CRG_IMSIC_CLK_CTL		CRG_REG(0x228)
#define CRG_CPU_CHI_CLK_CTL		CRG_REG(0x22C)
#define CRG_RMU_AXI_CLK_DIV		CRG_REG(0x300)
#define CRG_RMU_AHB_CLK_DIV		CRG_REG(0x304)
#define CRG_RMU_APB_CLK_DIV		CRG_REG(0x308)
#define CRG_RMU_LPC_CLK_DIV		CRG_REG(0x30C)
#define CRG_RMU_CLK_SEL			CRG_REG(0x310)
#define CRG_RMU_eFuse_NS_CLK_SEL	CRG_REG(0x314)
#define CRG_RMU_SRAM_CLK_EN		CRG_REG(0x320)
#define CRG_RMU_QSPI_CLK_EN		CRG_REG(0x324)
#define CRG_RMU_eFuse_NS_CLK_EN		CRG_REG(0x328)
#define CRG_RMU_STM_CLK_EN		CRG_REG(0x32C)
#define CRG_RMU_LPC_CLK_EN		CRG_REG(0x334)
#define CRG_RMU_eSPI_CLK_EN		CRG_REG(0x338)
#define CRG_RMU_PVTC_CLK_EN		CRG_REG(0x33C)
#define CRG_RMU_UART0_CLK_EN		CRG_REG(0x340)
#define CRG_RMU_UART1_CLK_EN		CRG_REG(0x344)
#define CRG_RMU_Timer_S_CLK_EN		CRG_REG(0x348)
#define CRG_RMU_Spinlock_CLK_EN		CRG_REG(0x34C)
#define CRG_RMU_Mailbox_S_CLK_EN	CRG_REG(0x350)
#define CRG_RMU_Mailbox_NS_CLK_EN	CRG_REG(0x354)
#define CRG_RMU_PIC_CLK_EN		CRG_REG(0x358)
#define CRG_RMU_HAP_CLK_EN		CRG_REG(0x35C)
#define CRG_PCIE0_BUS_CLK_CTL		CRG_REG(0x400)
#define CRG_PCIE1_BUS_CLK_CTL		CRG_REG(0x404)
#define CRG_PCIE2_BUS_CLK_CTL		CRG_REG(0x408)
#define CRG_PCIE3_BUS_CLK_CTL		CRG_REG(0x40C)
#define CRG_PCIE0_AXI_CLK_CTL		CRG_REG(0x410)
#define CRG_PCIE1_AXI_CLK_CTL		CRG_REG(0x414)
#define CRG_PCIE2_AXI_CLK_CTL		CRG_REG(0x418)
#define CRG_PCIE3_AXI_CLK_CTL		CRG_REG(0x41C)
#define CRG_MPHY0_CLK_CTL		CRG_REG(0x420)
#define CRG_MPHY1_CLK_CTL		CRG_REG(0x424)
#define CRG_MPHY2_CLK_CTL		CRG_REG(0x428)
#define CRG_TCU0_CLK_CTL		CRG_REG(0x430)
#define CRG_TCU1_CLK_CTL		CRG_REG(0x434)
#define CRG_PCIE4_BUS_CLK_CTL		CRG_REG(0x600)
#define CRG_PCIE5_BUS_CLK_CTL		CRG_REG(0x604)
#define CRG_PCIE6_BUS_CLK_CTL		CRG_REG(0x608)
#define CRG_PCIE7_BUS_CLK_CTL		CRG_REG(0x60C)
#define CRG_PCIE8_BUS_CLK_CTL		CRG_REG(0x610)
#define CRG_PCIE9_BUS_CLK_CTL		CRG_REG(0x614)
#define CRG_PCIE4_AUX_CLK_CTL		CRG_REG(0x618)
#define CRG_PCIE5_AUX_CLK_CTL		CRG_REG(0x61C)
#define CRG_PCIE6_AUX_CLK_CTL		CRG_REG(0x620)
#define CRG_PCIE7_AUX_CLK_CTL		CRG_REG(0x624)
#define CRG_PCIE8_AUX_CLK_CTL		CRG_REG(0x628)
#define CRG_PCIE9_AUX_CLK_CTL		CRG_REG(0x62C)
#define CRG_PCIE_TCU2_CLK_CTL		CRG_REG(0x630)
#define CRG_PCIE_SUBLINK_CLK_CTL	CRG_REG(0x634)
#define CRG_PCIE_SYS_CLK_CTL		CRG_REG(0x638)
#define CRG_COMBPHY3_CLK_CTL		CRG_REG(0x63C)
#define CRG_COMBPHY4_CLK_CTL		CRG_REG(0x640)
#define CRG_COMBPHY5_CLK_CTL		CRG_REG(0x644)
#define	CRG_PERI_AHB_CLK_CTL		CRG_REG(0x810)
#define	CRG_PERI_SPI0_CLK_CTL		CRG_REG(0x820)
#define	CRG_PERI_SPI1_CLK_CTL		CRG_REG(0x824)
#define	CRG_PERI_SPI2_CLK_CTL		CRG_REG(0x828)
#define	CRG_PERI_SPI3_CLK_CTL		CRG_REG(0x82C)
#define	CRG_PERI_SMBUS0_CLK_CTL		CRG_REG(0x840)
#define	CRG_PERI_SMBUS1_CLK_CTL		CRG_REG(0x844)
#define CRG_PERI_I3C0_CLK_CTL		CRG_REG(0x860)
#define CRG_PERI_I3C1_CLK_CTL		CRG_REG(0x864)
#define CRG_PERI_I2C0_CLK_CTL		CRG_REG(0x880)
#define CRG_PERI_I2C1_CLK_CTL		CRG_REG(0x884)
#define CRG_PERI_I2C2_CLK_CTL		CRG_REG(0x888)
#define CRG_PERI_I2C3_CLK_CTL		CRG_REG(0x88C)
#define CRG_PERI_I2C4_CLK_CTL		CRG_REG(0x890)
#define CRG_PERI_I2C5_CLK_CTL		CRG_REG(0x894)
#define CRG_PERI_UART0_CLK_CTL		CRG_REG(0x8A0)
#define CRG_PERI_UART1_CLK_CTL		CRG_REG(0x8A4)
#define CRG_PERI_UART2_CLK_CTL		CRG_REG(0x8A8)
#define CRG_PERI_UART3_CLK_CTL		CRG_REG(0x8AC)
#define CRG_PERI_GPIO0_CLK_CTL		CRG_REG(0x8C0)
#define CRG_PERI_GPIO1_CLK_CTL		CRG_REG(0x8C4)
#define CRG_PERI_GPIO2_CLK_CTL		CRG_REG(0x8C8)
#define CRG_PERI_GPIO3_CLK_CTL		CRG_REG(0x8CC)
#define CRG_PERI_GPIO4_CLK_CTL		CRG_REG(0x8D0)
#define CRG_PERI_WDT0_CLK_CTL		CRG_REG(0x8E0)
#define CRG_PERI_WDT1_CLK_CTL		CRG_REG(0x8E4)
#define CRG_PERI_WDT2_CLK_CTL		CRG_REG(0x8E8)
#define CRG_PERI_WDT3_CLK_CTL		CRG_REG(0x8EC)
#define CRG_PERI_WDT4_CLK_CTL		CRG_REG(0x8F0)
#define CRG_PERI_WDT5_CLK_CTL		CRG_REG(0x8F4)
#define CRG_PERI_WDT6_CLK_CTL		CRG_REG(0x8F8)
#define CRG_PERI_WDT7_CLK_CTL		CRG_REG(0x8FC)
#define CRG_PERI_TIMER0_CLK_CTL		CRG_REG(0x900)
#define CRG_PERI_TIMER1_CLK_CTL		CRG_REG(0x904)
#define CRG_PERI_TIMER2_CLK_CTL		CRG_REG(0x908)
#define CRG_PERI_TIMER3_CLK_CTL		CRG_REG(0x90C)
#define CRG_PERI_TIMER4_CLK_CTL		CRG_REG(0x910)
#define CRG_PERI_TIMER5_CLK_CTL		CRG_REG(0x914)
#define CRG_PERI_TIMER6_CLK_CTL		CRG_REG(0x918)
#define CRG_PERI_TIMER7_CLK_CTL		CRG_REG(0x91C)
#define CRG_PERI_TIMER8_CLK_CTL		CRG_REG(0x920)
#define CRG_PERI_TIMER9_CLK_CTL		CRG_REG(0x924)
#define CRG_PERI_TIMER10_CLK_CTL	CRG_REG(0x928)
#define CRG_PERI_TIMER11_CLK_CTL	CRG_REG(0x92C)
#define CRG_PERI_TIMER12_CLK_CTL	CRG_REG(0x930)
#define CRG_PERI_TIMER13_CLK_CTL	CRG_REG(0x934)
#define CRG_PERI_TIMER14_CLK_CTL	CRG_REG(0x938)
#define CRG_PERI_TIMER15_CLK_CTL	CRG_REG(0x93C)
#define CRG_PERI_TIMER16_CLK_CTL	CRG_REG(0x940)
#define CRG_PERI_TIMER17_CLK_CTL	CRG_REG(0x944)
#define CRG_PERI_TIMER18_CLK_CTL	CRG_REG(0x948)
#define CRG_PERI_TIMER19_CLK_CTL	CRG_REG(0x94C)
#define CRG_PERI_TIMER20_CLK_CTL	CRG_REG(0x950)
#define CRG_PERI_TIMER21_CLK_CTL	CRG_REG(0x954)
#define CRG_PERI_TIMER22_CLK_CTL	CRG_REG(0x958)
#define CRG_PERI_TIMER23_CLK_CTL	CRG_REG(0x95C)
#define CRG_PERI_TIMER24_CLK_CTL	CRG_REG(0x960)
#define CRG_PERI_TIMER25_CLK_CTL	CRG_REG(0x964)
#define CRG_PERI_TIMER26_CLK_CTL	CRG_REG(0x968)
#define CRG_PERI_TIMER27_CLK_CTL	CRG_REG(0x96C)
#define CRG_PERI_TIMER28_CLK_CTL	CRG_REG(0x970)
#define CRG_PERI_TIMER29_CLK_CTL	CRG_REG(0x974)
#define CRG_PERI_TIMER30_CLK_CTL	CRG_REG(0x978)
#define CRG_PERI_TIMER31_CLK_CTL	CRG_REG(0x97C)
#define CRG_PERI_DMAC_CLK_CTL		CRG_REG(0x9C0)
#define CRG_PERI_GMAC_CLK_CTL		CRG_REG(0x9E0)

#define CRG_CPU_SUB_SW_RESET		CRG_REG(0x2100)
#define CRG_PCIE_TOP_SW_RESET		CRG_REG(0x2104)
#define CRG_PCIE_BOT_SW_RESET		CRG_REG(0x2108)
#define CRG_PERI_SUB_SW_RESET		CRG_REG(0x210C)
#define CRG_MESH_SUB_SW_RESET		CRG_REG(0x2110)
#define CRG_DDR_SUB_SW_RESET		CRG_REG(0x2114)
#define CRG_CPU_SUB_SW_RESET		CRG_REG(0x2100)
#define CRG_CLUSTER0_SW_RESET		CRG_REG(0x2200)
#define CRG_CLUSTER1_SW_RESET		CRG_REG(0x2204)
#define CRG_CLUSTER2_SW_RESET		CRG_REG(0x2208)
#define CRG_CLUSTER3_SW_RESET		CRG_REG(0x220C)
#define CRG_CLUSTER4_SW_RESET		CRG_REG(0x2210)
#define CRG_CLUSTER5_SW_RESET		CRG_REG(0x2214)
#define CRG_CLUSTER6_SW_RESET		CRG_REG(0x2218)
#define CRG_CLUSTER7_SW_RESET		CRG_REG(0x221C)
#define CRG_CPU_SW_RESET		CRG_REG(0x2220)
#define CRG_CPU_RAS_SW_RESET            CRG_REG(0x2240)
#define CRG_RMU_SRAM_SW_RSTN		CRG_REG(0x2320)
#define CRG_RMU_QSPI_SW_RSTN		CRG_REG(0x2324)
#define CRG_RMU_eFuse_NS_SW_RSTN	CRG_REG(0x2328)
#define CRG_RMU_LPC_SW_RSTN		CRG_REG(0x2334)
#define CRG_RMU_eSPI_SW_RSTN		CRG_REG(0x2338)
#define CRG_RMU_PVTC_SW_RSTN		CRG_REG(0x233C)
#define CRG_RMU_UART0_SW_RSTN		CRG_REG(0x2340)
#define CRG_RMU_UART1_SW_RSTN		CRG_REG(0x2344)
#define CRG_RMU_Timer_S_SW_RSTN		CRG_REG(0x2348)
#define CRG_RMU_Spinlock_SW_RSTN	CRG_REG(0x234C)
#define CRG_RMU_Mailbox_S_SW_RSTN	CRG_REG(0x2350)
#define CRG_RMU_Mailbox_NS_SW_RSTN	CRG_REG(0x2354)
#define CRG_RMU_PIC_SW_RSTN		CRG_REG(0x2358)
#define CRG_PCIE0_SW_RESET		CRG_REG(0x2400)
#define CRG_PCIE1_SW_RESET		CRG_REG(0x2404)
#define CRG_PCIE2_SW_RESET		CRG_REG(0x2408)
#define CRG_PCIE3_SW_RESET		CRG_REG(0x240C)
#define CRG_MPHY0_SW_RESET		CRG_REG(0x2420)
#define CRG_MPHY1_SW_RESET		CRG_REG(0x2424)
#define CRG_MPHY2_SW_RESET		CRG_REG(0x2428)
#define CRG_TCU0_SW_RESET		CRG_REG(0x2430)
#define CRG_TCU1_SW_RESET		CRG_REG(0x2434)
#define CRG_PCIE4_SW_RESET		CRG_REG(0x2600)
#define CRG_PCIE5_SW_RESET		CRG_REG(0x2604)
#define CRG_PCIE6_SW_RESET		CRG_REG(0x2608)
#define CRG_PCIE7_SW_RESET		CRG_REG(0x260C)
#define CRG_PCIE8_SW_RESET		CRG_REG(0x2610)
#define CRG_PCIE9_SW_RESET		CRG_REG(0x2614)
#define CRG_PCIE_TCU2_SW_RESET		CRG_REG(0x2634)
#define CRG_PCIE_SUBLINK_SW_RESET	CRG_REG(0x2638)
#define CRG_PCIE_SYS_SW_RESET		CRG_REG(0x263C)
#define CRG_COMBPHY3_APB_SW_RESET	CRG_REG(0x2640)
#define CRG_COMBPHY4_APB_SW_RESET	CRG_REG(0x2644)
#define CRG_COMBPHY5_APB_SW_RESET	CRG_REG(0x2648)
#define CRG_COMBPHY3_PHYRESETN_SW_RESET	CRG_REG(0x264C)
#define CRG_COMBPHY4_PHYRESETN_SW_RESET	CRG_REG(0x2650)
#define CRG_COMBPHY5_PHYRESETN_SW_RESET	CRG_REG(0x2654)
#define CRG_PERI_SPI0_SW_RESET		CRG_REG(0x2820)
#define CRG_PERI_SPI1_SW_RESET		CRG_REG(0x2824)
#define CRG_PERI_SPI2_SW_RESET		CRG_REG(0x2828)
#define CRG_PERI_SPI3_SW_RESET		CRG_REG(0x282C)
#define CRG_PERI_SMBUS0_SW_RESET	CRG_REG(0x2840)
#define CRG_PERI_SMBUS1_SW_RESET	CRG_REG(0x2844)
#define CRG_PERI_I3C0_SW_RESET		CRG_REG(0x2860)
#define CRG_PERI_I3C1_SW_RESET		CRG_REG(0x2864)
#define CRG_PERI_I2C0_SW_RESET		CRG_REG(0x2880)
#define CRG_PERI_I2C1_SW_RESET		CRG_REG(0x2884)
#define CRG_PERI_I2C2_SW_RESET		CRG_REG(0x2888)
#define CRG_PERI_I2C3_SW_RESET		CRG_REG(0x288C)
#define CRG_PERI_I2C4_SW_RESET		CRG_REG(0x2890)
#define CRG_PERI_I2C5_SW_RESET		CRG_REG(0x2894)
#define CRG_PERI_UART0_SW_RESET		CRG_REG(0x28A0)
#define CRG_PERI_UART1_SW_RESET		CRG_REG(0x28A4)
#define CRG_PERI_UART2_SW_RESET		CRG_REG(0x28A8)
#define CRG_PERI_UART3_SW_RESET		CRG_REG(0x28AC)
#define CRG_PERI_GPIO0_SW_RESET		CRG_REG(0x28C0)
#define CRG_PERI_GPIO1_SW_RESET		CRG_REG(0x28C4)
#define CRG_PERI_GPIO2_SW_RESET		CRG_REG(0x28C8)
#define CRG_PERI_GPIO3_SW_RESET		CRG_REG(0x28CC)
#define CRG_PERI_GPIO4_SW_RESET		CRG_REG(0x28D0)
#define CRG_PERI_WDT0_SW_RESET		CRG_REG(0x28E0)
#define CRG_PERI_WDT1_SW_RESET		CRG_REG(0x28E4)
#define CRG_PERI_WDT2_SW_RESET		CRG_REG(0x28E8)
#define CRG_PERI_WDT3_SW_RESET		CRG_REG(0x28EC)
#define CRG_PERI_WDT4_SW_RESET		CRG_REG(0x28F0)
#define CRG_PERI_WDT5_SW_RESET		CRG_REG(0x28F4)
#define CRG_PERI_WDT6_SW_RESET		CRG_REG(0x28F8)
#define CRG_PERI_WDT7_SW_RESET		CRG_REG(0x28FC)
#define CRG_PERI_GTIMER0_SW_RESET	CRG_REG(0x2900)
#define CRG_PERI_GTIMER1_SW_RESET	CRG_REG(0x2920)
#define CRG_PERI_GTIMER2_SW_RESET	CRG_REG(0x2940)
#define CRG_PERI_GTIMER3_SW_RESET	CRG_REG(0x2960)
#define CRG_PERI_DMAC_SW_RESET		CRG_REG(0x29C0)
#define CRG_PERI_GMAC_SW_RESET		CRG_REG(0x29E0)
#define CRG_PERI_TBU_SW_RESET		CRG_REG(0x29F0)
#define CRG_PERI_TBU_ADB_SW_RESET	CRG_REG(0x29F4)

/* XXX_CLK_CTL */
#define CRG_CLKENABLE(n)		_BV(n)
#define CRG_CLKDIV0_OFFSET		4
#define CRG_CLKDIV0_MASK		REG_12BIT_MASK
#define CRG_CLKDIV0(value)		_SET_FV(CRG_CLKDIV0, value)
#define CRG_CLKDIV1_OFFSET		16
#define CRG_CLKDIV1_MASK		REG_8BIT_MASK
#define CRG_CLKDIV1(value)		_SET_FV(CRG_CLKDIV1, value)
#define CRG_CLKSEL_OFFSET		24
#define CRG_CLKSEL_MASK			REG_8BIT_MASK
#define CRG_CLKSEL(value)		_SET_FV(CRG_CLKSEL, value)

/* XXX_SW_RESET */
#define CRG_RSTN(n)			_BV(n)

#ifdef CONFIG_CRCNTL_TRACE
void crg_trace(bool enabling, const char *name);
#else
#define crg_trace(enabling, name)	do { } while (0)
#endif

#endif /* __K1MATRIX_CRG_H_INCLUDE__ */
