obj-y :=

obj-$(CONFIG_DW_UMCTL2_DDR4) += dw_umctl2_ddr4.rel
obj-$(CONFIG_DW_UMCTL2_DDR5) += dwc_ddr54_prgm_regb_addrmap.rel
obj-$(CONFIG_DW_UMCTL2_DDR5) += dwc_ddr54_prgm_regb_port.rel
obj-$(CONFIG_DW_UMCTL2_DDR5) += dwc_ddr54_prgm_regb_freq.rel
obj-$(CONFIG_DW_UMCTL2_DDR5) += dwc_ddr54_prgm_regb_ddrc.rel
obj-$(CONFIG_DW_UMCTL2_DDR5) += dwc_ddr54_ctrl.rel
obj-$(CONFIG_DW_UMCTL2_DDR5) += dwc_ddr5_ucode.rel
obj-$(CONFIG_DW_UMCTL2_DDR5) += dwc_ddr5_sw_cmd.rel
obj-$(CONFIG_DW_UMCTL2_DDR5) += dwc_ddr54_para_cfg.rel
