obj-y :=

obj-y += coresight.rel
obj-$(CONFIG_CORESIGHT_TPIU) += coresight_tpiu.rel
obj-$(CONFIG_CORESIGHT_ETB) += coresight_etb.rel
obj-$(CONFIG_CORESIGHT_ETM) += coresight_etm.rel
obj-$(CONFIG_CORESIGHT_FUNNEL) += coresight_funnel.rel
obj-$(CONFIG_CORESIGHT_REPLICATOR) += coresight_replicator.rel
obj-$(CONFIG_CORESIGHT_TMC) += coresight_tmc.rel
obj-$(CONFIG_CORESIGHT_STM) += coresight_stm.rel
obj-$(CONFIG_CORESIGHT_ETR) += coresight_etr.rel
obj-$(CONFIG_CORESIGHT_PMU) += coresight_pmu.rel
obj-$(CONFIG_CORESIGHT_CTI) += coresight_cti.rel
obj-$(CONFIG_CORESIGHT_DBG_CPUv80A) += coresight_dbg_cpuv80a.rel
obj-$(CONFIG_CORESIGHT_MEM_AP) += coresight_mem_ap.rel
obj-$(CONFIG_CORESIGHT_ENCODER) += coresight_encoder.rel
obj-$(CONFIG_CORESIGHT_atbbridge) += coresight_atbbridge.rel
