obj-y += mach.rel
obj-y += tsc.rel
obj-$(CONFIG_MEM) += mem.rel
obj-$(CONFIG_TIMER) += gpt.rel
obj-$(CONFIG_SBI) += sbi.rel

obj-$(CONFIG_DPULP_TMR) += tmr.rel
obj-$(CONFIG_DPULP_TCSR) += tcsr.rel
obj-$(CONFIG_DPULP_CRU) += cru.rel
obj-$(CONFIG_DPULP_CRU) += clk.rel
obj-$(CONFIG_DPULP_UART) += uart.rel
obj-$(CONFIG_DPULP_SPI_FLASH) += flash.rel
obj-$(CONFIG_DPULP_SSI_FLASH) += ssi.rel
obj-$(CONFIG_DPULP_SD) += sd.rel
obj-$(CONFIG_DPULP_DDR) += ddr.rel
obj-$(CONFIG_DPULP_RIO) += rio.rel
obj-$(CONFIG_DPULP_PCIE) += pcie.rel
