obj-y += mach.rel
obj-$(CONFIG_CLK) += clk.rel pcc.rel scg.rel
obj-$(CONFIG_GPIO) += gpio.rel
obj-$(CONFIG_MEM) += mem.rel
obj-$(CONFIG_LPUART) += uart.rel lpuart.rel
obj-$(CONFIG_IRQC_EVENT) += event.rel
