obj-y :=

CFLAGS += -I$(srctree)/include/tests/riscv/iommu

obj-y += build_ddt.o
obj-y += build_g_stage_pt.o
obj-y += build_pdt.o
obj-y += build_s_stage_pt.o
obj-y += build_vs_stage_pt.o
obj-y += translate_gpa.o
