CFLAGS := -O0 -g -Wall -Werror -I../../../../include/tests/riscv/iommu
CC := gcc
NAME := tables
SRCS = build_ddt.c build_pdt.c build_g_stage_pt.c build_s_stage_pt.c build_vs_stage_pt.c translate_gpa.c
OBJS = $(SRCS:.c=.o)

lib: lib$(NAME).a

lib$(NAME).a: $(OBJS)
	ar rcD $@ $^ > /dev/null 2>&1
	ranlib $@

OBJ_APP = $(SRCS_APP:.c=.o)

clean:
	$(RM) *.o *.a* tags log
