CONFIG_DHRYSTONE_BESTEFFORT=1

PROGS=dhrystone.elf linpack.elf

include ../Makefile.bench

all: $(PROGS)

CFLAGS_dhrystone_besteffort=\
	-O2 -DREG=register
CFLAGS_dhrystone_groundrule=\
	-fno-inline
ifdef CONFIG_DHRYSTONE_BESTEFFORT
CFLAGS_dhrystone_basic=$(CFLAGS_dhrystone_besteffort)
else
CFLAGS_dhrystone_basic=$(CFLAGS_dhrystone_groundrule)
endif

CFLAGS_dhrystone=\
	$(CFLAGS_dhrystone_basic) \
	-DCONFIG_DHRYSTONE_TIME_TIME=1 \
	-I../../include

CFLAGS_linpack=\
	-I../../include

clean:
	@rm -f $(PROGS)
	@rm -f *.unstrip
	@rm -f *.o
	@rm -f *.debug
