all: linpack

CC=$(CROSS_COMPILE)gcc
CFLAGS=-O2 -DHOSTED -DCONFIG_DHRYSTONE_TIME_CLOCK=1 -DCONFIG_FP=1 -fno-inline -DREG=register -I../../include
LDFLAGS=-s

linpack.o: linpack.c
	$(CC) $(CFLAGS) -c $< -o $@

linpack: linpack.o
	$(CC) $(LDFLAGS) $< -o $@

clean:
	@rm -f linpack
	@rm -f *.o
