CONFIG_DHRYSTONE_BESTEFFORT=1
CONFIG_DHRYSTONE_REGISTER=1
CONFIG_DHRYSTONE_MICROSECOND=1
CONFIG_DHRYSTONE_OPTIMISED=3

PROGS=dhrystone.elf linpack.elf

include ../Makefile.bench

all: $(PROGS)

ifeq ($(CONFIG_DHRYSTONE_OPTIMISED),)
CFLAGS_dhrystone_opt=-O -DDHRYSTONE_OPT=\"\"
endif
ifeq ($(CONFIG_DHRYSTONE_OPTIMISED),0)
CFLAGS_dhrystone_opt=-O0 -DDHRYSTONE_OPT=\"0\"
endif
ifeq ($(CONFIG_DHRYSTONE_OPTIMISED),1)
CFLAGS_dhrystone_opt=-O1 -DDHRYSTONE_OPT=\"1\"
endif
ifeq ($(CONFIG_DHRYSTONE_OPTIMISED),2)
CFLAGS_dhrystone_opt=-O2 -DDHRYSTONE_OPT=\"2\"
endif
ifeq ($(CONFIG_DHRYSTONE_OPTIMISED),3)
CFLAGS_dhrystone_opt=-O3 -DDHRYSTONE_OPT=\"3\"
endif
ifdef CONFIG_DHRYSTONE_REGISTER
CFLAGS_dhrystone_reg=-DREG=register
else
CFLAGS_dhrystone_reg=
endif
CFLAGS_dhrystone_besteffort=\
	$(CFLAGS_dhrystone_opt) $(CFLAGS_dhrystone_reg) -finline-limit=0
CFLAGS_dhrystone_groundrule=\
	$(CFLAGS_dhrystone_opt) -DCNNT -fno-inline
ifdef CONFIG_DHRYSTONE_BESTEFFORT
CFLAGS_dhrystone_basic=$(CFLAGS_dhrystone_besteffort)
else
CFLAGS_dhrystone_basic=$(CFLAGS_dhrystone_groundrule)
endif

ifdef CONFIG_DHRYSTONE_MICROSECOND
CFLAGS_dhrystone_time=\
	-DCONFIG_DHRYSTONE_TIME_CLOCK \
	-DCONFIG_DHRYSTONE_WARMUPS=10000
else
CFLAGS_dhrystone_time=-DCONFIG_DHRYSTONE_TIME_TIME
endif

CFLAGS_dhrystone=\
	$(CFLAGS_dhrystone_basic) \
	$(CFLAGS_dhrystone_time) \
	-I../../include

CFLAGS_linpack=\
	-I../../include

clean:
	@rm -f $(PROGS)
	@rm -f *.unstrip
	@rm -f *.o
	@rm -f *.debug
