obj-y :=

CFLAGS_dhrystone.o += -DREG=register
obj-$(CONFIG_DHRYSTONE) += dhrystone.rel

obj-$(CONFIG_HANOITOWER) += hanoitower.rel

obj-$(CONFIG_COREMARK) += coremark/

obj-$(CONFIG_C_FFT) += c_fft/

